build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.18-openshift-4.12
images:
  items:
  - dockerfile_path: Containerfile
    to: nvidia-ci
  run_if_changed: x^
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.21.0-0
        stream: 4-stable
        upper: 4.22.0-0
resources:
  '*':
    limits:
      memory: 2Gi
    requests:
      cpu: 2000m
      memory: 2Gi
tests:
- as: nvidia-dra-gpu-e2e
  cron: 0 6 * * 3
  reporter_config:
    channel: '#wg-nvidia-gpu-nno-operator-ci'
    job_states_to_report:
    - failure
    - error
    - aborted
    report_template: |
      {{if eq .Status.State "success"}}
        :white_check_mark: Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> :white_check_mark:
      {{else}}
        :warning: Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> :warning:
        {{if eq .Status.State "aborted"}}
          The job was aborted, check for orphaned cloud resources.
        {{end}}
      {{end}}
  steps:
    cluster_profile: aws-edge-infra
    env:
      BASE_DOMAIN: edge-sro.rhecoeng.com
      COMPUTE_NODE_REPLICAS: "1"
      COMPUTE_NODE_TYPE: g4dn.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m5d.2xlarge
      CONTROL_PLANE_REPLICAS: "1"
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-conf-aws
    - chain: ipi-install
    test:
    - as: nvidia-dra-gpu-e2e-tests
      commands: |
        set -eo pipefail

        export TEST_TRACE="true"
        export TEST_VERBOSE="true"
        export NVIDIAGPU_CLEANUP=false
        export TEST_FEATURES=nvidiagpu
        make run-tests

        export DRA_CHART_VERSION=$(./scripts/get-latest-dra-chart.sh)
        export DRA_CHART_SOURCE=oci://us-central1-docker.pkg.dev/k8s-staging-images/dra-driver-nvidia/charts/dra-driver-nvidia-gpu
        export TEST_FEATURES=dra

        export TEST_LABELS=dra-imex
        make run-tests

        export TEST_LABELS=dra-gpu
        make run-tests
      from: nvidia-ci
      resources:
        requests:
          cpu: 2000m
          memory: 2Gi
zz_generated_metadata:
  branch: main
  org: rh-ecosystem-edge
  repo: nvidia-ci
  variant: 4.21-dra
