build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.18-openshift-4.12
images:
- dockerfile_path: Containerfile
  to: nvidia-ci
releases:
  arm64-latest:
    prerelease:
      architecture: arm64
      product: ocp
      version_bounds:
        lower: 4.14.0-0
        stream: 4-stable
        upper: 4.15.0-0
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.14.0-0
        stream: 4-stable
        upper: 4.15.0-0
resources:
  '*':
    limits:
      memory: 2Gi
    requests:
      cpu: 2000m
      memory: 2Gi
tests:
- always_run: false
  as: nvidia-gpu-operator-e2e-master
  steps:
    cluster_profile: aws-edge-infra
    env:
      BASE_DOMAIN: edge-sro.rhecoeng.com
      NVIDIAGPU_DEPLOY_FROM_BUNDLE: "true"
    workflow: nvidia-gpu-operator-e2e-aws
- always_run: false
  as: nvidia-gpu-operator-e2e-25-10-x
  steps:
    cluster_profile: aws-edge-infra
    env:
      BASE_DOMAIN: edge-sro.rhecoeng.com
      NVIDIAGPU_SUBSCRIPTION_CHANNEL: v25.10
    workflow: nvidia-gpu-operator-e2e-aws
- always_run: false
  as: nvidia-gpu-operator-e2e-25-3-x
  steps:
    cluster_profile: aws-edge-infra
    env:
      BASE_DOMAIN: edge-sro.rhecoeng.com
      NVIDIAGPU_SUBSCRIPTION_CHANNEL: v25.3
    workflow: nvidia-gpu-operator-e2e-aws
- always_run: false
  as: nvidia-gpu-operator-e2e-arm64
  steps:
    cluster_profile: aws-edge-infra
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      AWS_REGION_OVERWRITE: us-east-1
      BASE_DOMAIN: edge-sro.rhecoeng.com
      COMPUTE_NODE_TYPE: g5g.2xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    workflow: nvidia-gpu-operator-e2e-aws
zz_generated_metadata:
  branch: main
  org: rh-ecosystem-edge
  repo: nvidia-ci
  variant: 4.14-stable
