base_images:
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
build_root:
  from_repository: true
canonical_go_repository: github.com/openshift/monitoring-plugin
images:
  items:
  - dockerfile_path: Dockerfile
    to: monitoring-plugin
  - dockerfile_path: Dockerfile.test
    to: monitoring-plugin-test
  - dockerfile_path: Dockerfile.mcp
    to: monitoring-console-plugin
  - context_dir: .
    dockerfile_path: web/cypress/Dockerfile
    to: monitoring-ui-tests-runner
promotion:
  to:
  - excluded_images:
    - monitoring-plugin-test
    name: 5.0-priv
    namespace: ocp-private
prowgen:
  private: true
releases:
  initial:
    integration:
      name: 5.0-priv
      namespace: ocp-private
  latest:
    integration:
      include_built_images: true
      name: 5.0-priv
      namespace: ocp-private
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 8Gi
tests:
- as: go-tests
  commands: |
    # The default GOFLAGS adds -mod=vendor while the monitoring-plugin
    # repository doesn't vendor the dependencies.
    unset GOFLAGS
    export GOCACHE=/tmp/go-build
    export GOLANGCI_LINT_CACHE=/tmp/go-build
    export GOMODCACHE=/tmp/go-mod
    make test-backend lint-backend
    git diff --exit-code
  container:
    from: src
- as: lint
  commands: |
    make lint-frontend
  container:
    from: monitoring-plugin-test
- as: translations
  commands: |
    make test-translations
  container:
    from: monitoring-plugin-test
- as: e2e-aws-ovn
  steps:
    cluster_profile: openshift-org-aws
    workflow: openshift-e2e-aws
- always_run: false
  as: e2e-aws-ovn-upgrade
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    workflow: openshift-upgrade-aws
- always_run: false
  as: e2e-hypershift-conformance
  optional: true
  steps:
    cluster_profile: hypershift-aws
    workflow: hypershift-aws-conformance
- as: verify-deps
  steps:
    env:
      CHECK_MOD_LIST: "false"
    test:
    - ref: go-verify-deps
- always_run: false
  as: e2e-monitoring
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-monitoring-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-coo
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-coo-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-incidents
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-incidents-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-alerts
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-alerts-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-dashboards
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-dashboards-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-metrics
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-metrics-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-monitoring-bvt
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-monitoring-bvt-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-monitoring-reg
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-monitoring-reg-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-virtualization
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-virtualization-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-perses
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-perses-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-monitoring-dev
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-monitoring-dev-ui
    workflow: ipi-aws
- always_run: false
  as: e2e-perses-dev
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    test:
    - ref: monitoring-plugin-tests-perses-dev-ui
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: openshift-priv
  repo: monitoring-plugin
