apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: art-cluster-admin
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: art-cluster-admins-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: art-cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: art-admins
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: art-admins-view-binding
  namespace: ci
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: art-admins
