plugins:
  stolostron/governance-policy-framework:
    plugins:
    - dco
    - blunderbuss
triggers:
- org_invite:
    prominent: {}
  repos:
  - stolostron/governance-policy-framework
  trusted_apps:
  - dependabot
  - openshift-merge-bot
