#!/bin/bash
set -euo pipefail

# Setup SSH key (add trailing newline if missing - Vault sync strips it)
cat /var/run/amd-ci/id_rsa > /tmp/id_rsa
echo "" >> /tmp/id_rsa
chmod 600 /tmp/id_rsa
mkdir -p ~/.ssh
cat > ~/.ssh/config <<EOF
Host ${REMOTE_HOST}
    User root
    IdentityFile /tmp/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
    ConnectTimeout 30
    ServerAliveInterval 10
    ServerAliveCountMax 3
    BatchMode yes
EOF
chmod 600 ~/.ssh/config

# Auto-detect machine_config_role: "master" for SNO, "worker" for multi-node
if [[ "${CTLPLANES:-1}" == "1" && "${WORKERS:-0}" == "0" ]]; then
    MACHINE_CONFIG_ROLE="master"
else
    MACHINE_CONFIG_ROLE="worker"
fi

# Generate cluster config file from environment variables
CONFIG_FILE=/tmp/cluster-config.yaml
cat > "${CONFIG_FILE}" <<EOF
# OpenShift Cluster Configuration - Generated by CI

# Required
ocp_version: "${OCP_CLUSTER_VERSION}"
pull_secret_path: /var/run/amd-ci/pull-secret

# Cluster settings
cluster_name: ${CLUSTER_NAME:-ocp}
domain: ${CLUSTER_DOMAIN:-example.com}
ctlplanes: ${CTLPLANES:-1}
workers: ${WORKERS:-0}

ctlplane:
  numcpus: 6
  memory: 18432

worker:
  numcpus: 4
  memory: 16384

disk_size: 120
network: default
api_ip: "${API_IP:-192.168.122.253}"

remote:
  host: "${REMOTE_HOST}"
  user: root
  ssh_key_path: /tmp/id_rsa

pci_devices: []
wait_timeout: 3600
version_channel: stable

operators:
  install: true
  gpu_operator_version: "${GPU_OPERATOR_VERSION:-1.4}"
  machine_config_role: "${MACHINE_CONFIG_ROLE}"
  driver_version: "${AMD_DRIVER_VERSION:-30.20.1}"
  enable_metrics: true
EOF

echo "Generated cluster config:"
cat "${CONFIG_FILE}"

# Install AMD GPU Operator and dependencies
make cluster-operators CONFIG_FILE_PATH="${CONFIG_FILE}"
