#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
set -x

LAB_CLOUD="${LAB_CLOUD:-}"
#RUNLOCAL="${RUNLOCAL:-1}"

SSH_ARGS="-i /bm/jh_priv_ssh_key -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
if [ -z "${RUNLOCAL:-}" ]; then
  bastion=$(cat "/bm/address")
else
  #bastion=localhost
  bastion=m42-h01-000-r760.rdu3.labs.perfscale.redhat.com
fi

REPO_NAME=${REPO_NAME:-}
PULL_NUMBER=${PULL_NUMBER:-}

#regulus_repo=/tmp/regulus-${LAB_CLOUD}-$(date +%s)
regulus_repo=/tmp/regulus-${LAB_CLOUD}

function clone-regulus {
  # Setup Bastion
  ssh ${SSH_ARGS} root@${bastion} "
    set -e
    set -o pipefail
    if [ -d  ${regulus_repo} ] ; then
        rm -fr  ${regulus_repo}
    fi
    git clone https://github.com/HughNhan/regulus.git --depth=1 --branch=${REG_BRANCH:-main} ${regulus_repo}
    cd ${regulus_repo}
    # REG_PR or PULL_NUMBER can't be set at the same time
    if [[ -n '${REG_PR}' ]]; then
     git pull origin pull/${REG_PR}/head:${REG_PR} --rebase
     git switch ${REG_PR}
    elif [[ -n '${PULL_NUMBER}' ]] && [[ '${REPO_NAME}' == 'regulus' ]]; then
     git pull origin pull/${PULL_NUMBER}/head:${PULL_NUMBER} --rebase
     git switch ${PULL_NUMBER}
    fi
    git branch
  "
}

clone-regulus

# ─────────────────────────────────────────────────────────────────────────────
# Regulus lab.config required var
# ─────────────────────────────────────────────────────────────────────────────
vars=(
  KUBECONFIG
  REG_KNI_USER
  REG_OCPHOST
  REG_DP
  OCP_WORKER_0
  OCP_WORKER_1
  OCP_WORKER_2
  BM_HOSTS
  REG_SRIOV_NIC
  REG_SRIOV_MTU
  REG_SRIOV_NIC_MODEL
  REG_MACVLAN_NIC
  REG_MACVLAN_MTU
  REG_DPDK_NIC_1
  REG_DPDK_NIC_2
  REG_DPDK_NIC_MODEL
  TREX_HOSTS
  TREX_SRIOV_INTERFACE_1
  TREX_SRIOV_INTERFACE_2
  TREX_DPDK_NIC_MODEL
  REM_DPDK_CONFIG
)

# ─────────────────────────────────────────────────────────────────────────────
# Generate lab.config
# ─────────────────────────────────────────────────────────────────────────────
if [ -e  /tmp/lab.config ]; then
    rm /tmp/lab.config
fi

cat > /tmp/lab.config <<EOF
# This file was generated by openshift-qe-installer-bm-day2-regulus-commands.sh
# It can be sourced by other scripts to import environment values.
EOF
for v in "${vars[@]}"; do
  # "${!v}" expands the variable whose name is in $v
  if [[ "$v" == "KUBECONFIG" ]]; then
    val=$KUBECONFIG_PATH  # Force override. idk why KUBECONFIG is wrong.
  else
    val="${!v:-}"
  fi

  # Force ~ at start to become /root/
  if [[ "$val" == ~* ]]; then
    val="${val/#\~\//\/root/}"
  fi

  # Escape any embedded double-quotes
  safe_val=${val//\"/\\\"}
  printf '%s="%s"\n' "$v" "$safe_val" >> /tmp/lab.config
done

# ─────────────────────────────────────────────────────────────────────────────
# Init regulus on the target cluster
# ───────────────────────────────────────────────────────────────────────────

function init-regulus {
  echo scp -q ${SSH_ARGS} /tmp/lab.config  root@${bastion}:${regulus_repo}/ 
  scp -q ${SSH_ARGS} /tmp/lab.config  root@${bastion}:${regulus_repo}/ 
  ssh ${SSH_ARGS} root@${bastion} "
    set -e
    set -o pipefail
    cd ${regulus_repo}
    source bootstrap.sh
    make init-lab 
    make init-jobs 
    # crcucible pods previlege
    kubectl label namespace crucible-rickshaw \
        pod-security.kubernetes.io/enforce=privileged \
        pod-security.kubernetes.io/enforce-version=v1.27 \
        --overwrite
    make jobs
  "
}

init-regulus
exit

cat /etc/os-release

if [ ${BAREMETAL} == "true" ]; then
  SSH_ARGS="-i /bm/jh_priv_ssh_key -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
  bastion="$(cat /bm/address)"
  # Copy over the kubeconfig
  if [ ! -f "${SHARED_DIR}/kubeconfig" ]; then
    ssh ${SSH_ARGS} root@$bastion "cat ${KUBECONFIG_PATH}" > /tmp/kubeconfig
    export KUBECONFIG=/tmp/kubeconfig
  else
    export KUBECONFIG=${SHARED_DIR}/kubeconfig
  fi
  # Setup socks proxy
  ssh ${SSH_ARGS} root@$bastion -fNT -D 12345
  export https_proxy=socks5://localhost:12345
  export http_proxy=socks5://localhost:12345
  oc --kubeconfig="$KUBECONFIG" config set-cluster bm --proxy-url=socks5://localhost:12345

  ssh ${SSH_ARGS} root@${bastion} "
      set -e 
      set -o pipefail
      mkdir /tmp/day2-regulus-baremetal
   "
else
  SSH_ARGS="-i /bm/jh_priv_ssh_key -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
  bastion="$(cat /bm/address)"
  ssh ${SSH_ARGS} root@${bastion} "
      set -e 
      set -o pipefail
      mkdir /tmp/day2-regulus-no-baremetal
   "
fi

oc config view
oc projects

# Install the Regulus 

sleep 10

# Regulus is ready


if [ ${BAREMETAL} == "true" ]; then
  # kill the ssh tunnel so the job completes
  pkill ssh
fi

