#!/bin/bash
set -x

# Setup SSH key (add trailing newline if missing - Vault sync strips it)
cat /var/run/amd-ci/id_rsa > /tmp/id_rsa
echo "" >> /tmp/id_rsa
chmod 600 /tmp/id_rsa
mkdir -p ~/.ssh
cat > ~/.ssh/config <<EOF
Host ${REMOTE_HOST}
    User root
    IdentityFile /tmp/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
    ConnectTimeout 30
    ServerAliveInterval 10
    ServerAliveCountMax 3
    BatchMode yes
EOF
chmod 600 ~/.ssh/config

# Configure remote host for SSH
ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${REMOTE_HOST} \
    "echo 'Host *' >> /etc/ssh/ssh_config && \
     echo '  StrictHostKeyChecking no' >> /etc/ssh/ssh_config && \
     echo '  UserKnownHostsFile /dev/null' >> /etc/ssh/ssh_config && \
     echo '#!/bin/sh' > /bin/sudo && \
     echo 'exec \"\$@\"' >> /bin/sudo && \
     chmod 755 /bin/sudo"

# Copy SSH key to remote host
scp -i /tmp/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/id_rsa root@${REMOTE_HOST}:~/.ssh/id_rsa
ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${REMOTE_HOST} \
    "chmod 600 ~/.ssh/id_rsa && \
     ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub && \
     chmod 600 ~/.ssh/authorized_keys 2>/dev/null || true && \
     grep -qF \"\$(cat ~/.ssh/id_rsa.pub)\" ~/.ssh/authorized_keys 2>/dev/null || cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
     chmod 600 ~/.ssh/authorized_keys"

# Generate cluster config file from environment variables
CONFIG_FILE=/tmp/cluster-config.yaml
cat > ${CONFIG_FILE} <<EOF
# OpenShift Cluster Configuration - Generated by CI

# Required
ocp_version: "${OCP_CLUSTER_VERSION}"
pull_secret_path: /var/run/amd-ci/pull-secret

# Cluster settings
cluster_name: ${CLUSTER_NAME:-ocp}
domain: ${CLUSTER_DOMAIN:-example.com}
ctlplanes: ${CTLPLANES:-1}
workers: ${WORKERS:-0}

ctlplane:
  numcpus: ${CTLPLANE_CPUS:-6}
  memory: ${CTLPLANE_MEMORY:-18432}

worker:
  numcpus: ${WORKER_CPUS:-4}
  memory: ${WORKER_MEMORY:-16384}

disk_size: ${DISK_SIZE:-120}
network: ${NETWORK:-default}
api_ip: "${API_IP:-192.168.122.253}"

remote:
  host: "${REMOTE_HOST}"
  user: root
  ssh_key_path: /tmp/id_rsa

pci_devices: []
wait_timeout: ${WAIT_TIMEOUT:-3600}
no_wait: false
version_channel: ${VERSION_CHANNEL:-stable}
EOF

echo "Generated cluster config:"
cat ${CONFIG_FILE}

# Deploy cluster using config file
make cluster-deploy CONFIG_FILE_PATH=${CONFIG_FILE}

