build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.22
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: firewatch-jira-cloud-token-validation
  cron: '@daily'
  steps:
    cluster_profile: aws-2
    env:
      FIREWATCH_JIRA_SERVER: https://redhat.atlassian.net
    test:
    - ref: firewatch-test-jira-token
  timeout: 10m0s
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: firewatch-jira-token-test
