plugins:
  RedHatInsights/lightspeed-advisor-on-premise-ocp:
    plugins:
    - trigger
triggers:
- repos:
  - RedHatInsights/lightspeed-advisor-on-premise-ocp
  trusted_apps:
  - openshift-merge-bot
