#!/usr/bin/env bash

set -Eeuo pipefail

export OS_CLIENT_CONFIG_FILE="${SHARED_DIR}/clouds.yaml"

OPENSTACK_EXTERNAL_NETWORK="${OPENSTACK_EXTERNAL_NETWORK:-$(<"${SHARED_DIR}/OPENSTACK_EXTERNAL_NETWORK")}"

declare OPENSTACK_EXTERNAL_NETWORK_ID
if [[ -n "$OPENSTACK_EXTERNAL_NETWORK" ]]; then
	OPENSTACK_EXTERNAL_NETWORK_ID=$(openstack network show "${OPENSTACK_EXTERNAL_NETWORK}" -f value -c id)
fi

cat <<< "$OPENSTACK_EXTERNAL_NETWORK_ID" > "${SHARED_DIR}/OPENSTACK_EXTERNAL_NETWORK_ID"

cat <<EOF
OPENSTACK_EXTERNAL_NETWORK_ID: $OPENSTACK_EXTERNAL_NETWORK_ID
EOF
