approve:
- ignore_review_state: true
  repos:
  - openshift/network-observability-flowlogs-pipeline
  require_self_approval: true
lgtm:
- repos:
  - openshift/network-observability-flowlogs-pipeline
  review_acts_as_lgtm: true
plugins:
  openshift/network-observability-flowlogs-pipeline:
    plugins:
    - approve
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift/network-observability-flowlogs-pipeline
  trusted_apps:
  - openshift-merge-bot
  - red-hat-konflux
