approve:
- repos:
  - openshift/cert-manager-operator-release
  require_self_approval: false
lgtm:
- repos:
  - openshift/cert-manager-operator-release
  review_acts_as_lgtm: true
plugins:
  openshift/cert-manager-operator-release:
    plugins:
    - approve
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift/cert-manager-operator-release
  trusted_apps:
  - red-hat-konflux
  - openshift-merge-bot
