#!/bin/bash
set -euxo pipefail; shopt -s inherit_errexit

typeset reportDir="${ARTIFACT_DIR}/obs-results"
mkdir -p "${reportDir}"

# shellcheck disable=SC2317
PropagateJunit () {
    mkdir -p "${SHARED_DIR}/junit"
    cp "${reportDir}"/*.xml "${SHARED_DIR}/junit/" || true
    true
}

# shellcheck disable=SC2317
CollectArtifacts () {
    cp "${reportDir}"/* "${ARTIFACT_DIR}/" || true
    true
}

trap '{ CollectArtifacts; PropagateJunit; true; }' EXIT

if [[ "${MAP_TESTS}" == 'true' ]]; then
    eval "$(
        typeset -a _fURL=()
        type -t wget 1>/dev/null && _fURL=(wget --timeout=30 -qO-) || _fURL=(curl --connect-timeout 10 --max-time 30 -fsSL)
        "${_fURL[@]}" \
            https://raw.githubusercontent.com/RedHatQE/OpenShift-LP-QE--Tools/refs/heads/main/libs/bash/ci-operator/interop/common/ExitTrap--PostProcessPrep.sh
    )"
    if type -t ExitTrap--PostProcessPrep 1>/dev/null; then
        trap '
            LP_IO__ET_PPP__NEW_TS_NAME="${DR__RP__CR_COMP_NAME}--%s" \
                ExitTrap--PostProcessPrep
            CollectArtifacts; PropagateJunit
        ' EXIT
    fi
fi

# ---------------------------------------------------------------------------
# 1. Kubeconfig — use writable $HOME/.kube, not image-owned /workspace/.kube
# ---------------------------------------------------------------------------
typeset kubeDir="${HOME}/.kube"
mkdir -p "${kubeDir}"
cp "${SHARED_DIR}/kubeconfig" "${kubeDir}/config"
export KUBECONFIG="${kubeDir}/config"

if [[ -f "${SHARED_DIR}/managed-cluster-kubeconfig" ]]; then
    cp "${SHARED_DIR}/managed-cluster-kubeconfig" "${kubeDir}/import-kubeconfig"
fi

# ---------------------------------------------------------------------------
# 2. Load options from SHARED_DIR (generated by acm-obs-odf-setup)
# ---------------------------------------------------------------------------
[[ -f "${SHARED_DIR}/acm-obs-options.json" ]] || {
    : 'ERROR: acm-obs-options.json not found — acm-obs-odf-setup must run first'
    exit 1
}

export OPTIONS="${SHARED_DIR}/acm-obs-options.json"
export REPORT_FILE="${reportDir}/results.xml"

# ---------------------------------------------------------------------------
# 3. Environment for the suite
# ---------------------------------------------------------------------------
export SKIP_INSTALL_STEP='true'
export SKIP_UNINSTALL_STEP='true'
export IS_CANARY_ENV='true'

# ---------------------------------------------------------------------------
# 4. Run the compiled Ginkgo test binary
# ---------------------------------------------------------------------------
typeset ginkgoBin='/usr/local/bin/ginkgo'
[[ -x "${ginkgoBin}" ]] || { : "ERROR: ginkgo binary not found at ${ginkgoBin}"; exit 1; }

typeset testBin='/workspace/opt/tests/observability-e2e-test.test'
[[ -f "${testBin}" ]] || { : "ERROR: compiled test binary not found at ${testBin}"; exit 1; }

typeset -i ginkgoRc=0
"${ginkgoBin}" \
    --v \
    --focus="${GINKGO_FOCUS}" \
    --skip="${GINKGO_SKIP}" \
    --timeout=6300s \
    --no-color \
    -nodes=1 \
    --output-dir="${reportDir}" \
    --junit-report=results.xml \
    "${testBin}" \
    -- -v=3 || ginkgoRc=$?

[[ -f "${reportDir}/results.xml" ]] || {
    : "ERROR: missing JUnit report ${reportDir}/results.xml (ginkgo exit=${ginkgoRc})"
    exit 1
}

typeset -i testCnt=0
testCnt="$(grep -c '<testcase' "${reportDir}/results.xml" || true)"
((testCnt > 0)) || {
    : "ERROR: Ginkgo focus/skip matched no specs (focus=${GINKGO_FOCUS} skip=${GINKGO_SKIP})"
    exit 1
}

cp "${reportDir}/results.xml" "${ARTIFACT_DIR}/junit_acm-observability.xml"

# Exit policy: if Ginkgo failed but produced JUnit with recorded failures,
# the suite ran and the failures are observability-specific — not an infra
# problem that other LP tests depend on. Return 0 so downstream steps
# continue; Firewatch classifies the failures from JUnit.
# If Ginkgo failed without producing any <failure> elements (e.g. runner
# crash, image pull error, timeout with no output), exit nonzero.
typeset -i failCnt=0
failCnt="$(grep -c '<failure' "${reportDir}/results.xml" || true)"

if ((ginkgoRc != 0 && failCnt > 0)); then
    : "Ginkgo exit=${ginkgoRc} with ${failCnt} failure(s) in JUnit — returning 0 for downstream steps"
    exit 0
fi

exit "${ginkgoRc}"
