#!/usr/bin/env groovy

def library_url = "${env.RELEASE_LIBRARY_URL}"
def library_ref = "${env.RELEASE_LIBRARY_REF}"

library "${library_url}@${library_ref}"

def templateBase = "cluster/ci/origin/config"

pipeline {
  agent any

  stages {
    stage("Import Relase Image") {
      steps {
        applyTemplate(this, "${templateBase}/release-base.yaml",
          "RELEASE_SRC_URL=${env.RELEASE_SRC_URL}",
          "RELEASE_SRC_REF=${env.RELEASE_SRC_REF}",
          "ORIGIN_RELEASE_IMAGE=${env.RELEASE_IMAGE}",
          "ORIGIN_RELEASE_TAG=${env.RELEASE_TAG}",
          "ORIGIN_SRC_URL=${env.ORIGIN_SRC_URL}")
        waitForTag(this, "origin-release", "${env.RELEASE_TAG}")
      }
    }
    stage("Build Release Base") {
      steps {
        runBuild(this, "release-base")
      }
    }
  }
}
