plugins:
  openshift-priv/cluster-resource-override-admission-operator:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - wip
    - yuks
