external_plugins:
  fleetshift:
  - endpoint: http://repo-brancher-controller
    events:
    - push
    name: repo-brancher-controller
plugins:
  fleetshift:
    plugins:
    - trigger
triggers:
- repos:
  - fleetshift
  trusted_apps:
  - dependabot
  - openshift-merge-bot
