approve:
- commandHelpLink: ""
  repos:
  - openshift-priv/ironic-rhcos-downloader
  require_self_approval: false
plugins:
  openshift-priv/ironic-rhcos-downloader:
    plugins:
    - approve
    - golint
    - goose
    - jira
    - owners-label
    - pony
    - sigmention
triggers:
- repos:
  - openshift-priv/ironic-rhcos-downloader
  trusted_apps:
  - openshift-merge-bot
