apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-ci
  namespace: openshift-gitops
spec:
  sourceRepos:
  - https://github.com/openshift/release.git
  destinations:
  - name: app.ci
    namespace: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: config.openshift.io
    kind: OAuth
  - group: imageregistry.operator.openshift.io
    kind: Config
  - group: machineconfiguration.openshift.io
    kind: KubeletConfig
  - group: operator.openshift.io
    kind: MachineConfiguration
  - group: operator.openshift.io
    kind: ClusterCSIDriver
  namespaceResourceWhitelist:
  - group: apps
    kind: DaemonSet
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: batch
    kind: CronJob
  - group: build.openshift.io
    kind: BuildConfig
  - group: cert-manager.io
    kind: Certificate
  - group: grafana.integreatly.org
    kind: GrafanaDashboard
  - group: grafana.integreatly.org
    kind: GrafanaDatasource
  - group: grafana.integreatly.org
    kind: Grafana
  - group: monitoring.coreos.com
    kind: PrometheusRule
  - group: image.openshift.io
    kind: ImageStream
  - group: monitoring.coreos.com
    kind: PodMonitor
  - group: monitoring.coreos.com
    kind: Probe
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: networking.k8s.io
    kind: Ingress
  - group: operators.coreos.com
    kind: OperatorGroup
  - group: operators.coreos.com
    kind: Subscription
  - group: policy
    kind: PodDisruptionBudget
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: route.openshift.io
    kind: Route
  - group: secrets-store.csi.x-k8s.io
    kind: SecretProviderClass
  - group: template.openshift.io
    kind: Template
  - group: observability.openshift.io
    kind: ClusterLogForwarder
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
