approve:
- repos:
  - stolostron/multicluster-mesh-addon
  require_self_approval: false
lgtm:
- repos:
  - stolostron/multicluster-mesh-addon
  review_acts_as_lgtm: true
plugins:
  stolostron/multicluster-mesh-addon:
    plugins:
    - dco
