tide:
  merge_method:
    stolostron/managed-serviceaccount-e2e: squash
  queries:
  - includedBranches:
    - backplane-2.10
    - backplane-2.11
    - backplane-2.6
    - backplane-2.8
    - backplane-2.9
    - release-2.11
    - release-2.13
    - release-2.14
    - release-2.15
    - release-2.16
    labels:
    - approved
    - lgtm
    missingLabels:
    - 'dco-signoff: no'
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - stolostron/managed-serviceaccount-e2e
