plugins:
  containers/bootc:
    plugins:
    - cat
    - dog
    - heart
    - golint
    - help
    - lifecycle
    - override
    - skip
    - trigger
    - wip
    - yuks
triggers:
- org_invite:
    prominent: {}
  repos:
  - containers/bootc
  trusted_apps:
  - openshift-merge-bot
