branch-protection:
  orgs:
    openshift:
      repos:
        configure-alertmanager-operator:
          branches:
            master:
              protect: true
              required_status_checks:
                contexts:
                - Red Hat Konflux / configure-alertmanager-operator-master-on-pull-request
                - ci/prow/images
tide:
  queries:
  - author: red-hat-konflux
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - openshift/configure-alertmanager-operator
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - openshift/configure-alertmanager-operator
