plugins:
  stolostron/multicloud-operators-subscription:
    plugins:
    - dco
    - blunderbuss
triggers:
- org_invite:
    prominent: {}
  repos:
  - stolostron/multicloud-operators-subscription
  trusted_apps:
  - magic-mirror-bot
  - openshift-merge-bot
