orgs:
  - org: openshift
    repos:
      - api
      - apiserver-network-proxy
      - assisted-installer-agent
      - aws-encryption-provider
      - aws-pod-identity-webhook
      - azure-kubernetes-kms
      - azure-workload-identity
      - bond-cni
      - cluster-authentication-operator
      - cluster-capi-operator
      - cluster-etcd-operator
      - cluster-image-registry-operator
      - cluster-ingress-operator
      - cluster-kube-apiserver-operator
      - cluster-network-operator
      - cluster-storage-operator
      - configmap-reload
      - console
      - containernetworking-plugins
      - csi-driver-nfs
      - csi-operator
      - egress-router-cni
      - gcp-workload-identity-federation-webhook
      - installer
      - kube-rbac-proxy
      - kubernetes-kube-storage-version-migrator
      - kubevirt-csi-driver
      - machine-config-operator
      - multus-admission-controller
      - multus-networkpolicy
      - must-gather
      - network-metrics-daemon
      - network-tools
      - networking-console-plugin
      - oc
      - oc-mirror
      - route-override-cni
      - whereabouts-cni
      - name: external-secrets-operator
        branches:
          - main
      - hypershift
      - name: zero-trust-workload-identity-manager
        branches:
          - main
  - org: openshift-priv
    repos:
      - api
      - apiserver-network-proxy
      - aws-encryption-provider
      - aws-pod-identity-webhook
      - azure-kubernetes-kms
      - azure-workload-identity
      - bond-cni
      - cluster-authentication-operator
      - cluster-capi-operator
      - cluster-etcd-operator
      - cluster-image-registry-operator
      - cluster-ingress-operator
      - cluster-kube-apiserver-operator
      - cluster-network-operator
      - cluster-storage-operator
      - configmap-reload
      - console
      - containernetworking-plugins
      - csi-driver-nfs
      - csi-operator
      - egress-router-cni
      - gcp-workload-identity-federation-webhook
      - installer
      - kube-rbac-proxy
      - kubernetes-kube-storage-version-migrator
      - kubevirt-csi-driver
      - machine-config-operator
      - multus-admission-controller
      - multus-networkpolicy
      - must-gather
      - network-metrics-daemon
      - network-tools
      - networking-console-plugin
      - oc
      - oc-mirror
      - ovn-kubernetes
      - route-override-cni
      - whereabouts-cni
