plugins:
  openshift-priv/stolostron-multicluster-role-assignment:
    plugins:
    - approve
    - assign
    - dco
    - golint
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - retitle
    - shrug
    - trigger
    - verify-owners
    - wip
triggers:
- repos:
  - openshift-priv/stolostron-multicluster-role-assignment
  trusted_apps:
  - openshift-merge-bot
