build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-ci-dast
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: dast
  steps:
    test:
    - ref: openshift-qe-security-tooling-dast
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: ssml
