prowgen:
  enable_secrets_store_csi_driver: true
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: profile01
  cron: 0 6 * * 0
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CLEAN_IAM: "true"
      DRY_RUN: "true"
      REGIONS: us-east-1,us-west-1,us-east-2,us-west-2
    workflow: rosa-aws-cleanup
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-e2e
  variant: cloud-resource-cleanup
