base_images:
  nested-podman:
    name: nested-podman
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.24-openshift-4.22
images:
  items:
  - dockerfile_path: Containerfile
    to: rosa-e2e
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make unit-test
  container:
    from: src
- as: lint
  commands: |
    unset GOFLAGS
    make lint
  container:
    from: src
- as: e2e-rosa-hcp-smoke
  run_if_changed: ^(pkg/|test/|Containerfile|go\.(mod|sum))
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: stable
      ENABLE_BILLING_ACCOUNT: "yes"
      HOSTED_CP: "true"
      LABEL_FILTER: Importance:Critical && Platform:HCP && (Area:ClusterLifecycle
        || Area:DataPlane || Area:ManagementPlane || Area:Upgrade)
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.21"
      REPLICAS: "3"
    workflow: rosa-e2e-hcp
- as: e2e-rosa-classic-smoke
  run_if_changed: ^(pkg/|test/|Containerfile|go\.(mod|sum))
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: stable
      HOSTED_CP: "false"
      LABEL_FILTER: Importance:Critical && Platform:Classic && (Area:ClusterLifecycle
        || Area:DataPlane || Area:ManagementPlane || Area:Upgrade)
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.21"
      REPLICAS: "3"
    workflow: rosa-e2e-classic
- as: rosa-ci-daily-status
  commands: scripts/ci-status-report.sh
  container:
    from: src
  cron: 0 14 * * *
  reporter_config:
    channel: '#wg-rosa-ci-enhancement'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: |-
      {{if eq .Status.State "success"}}:large_green_circle: *ROSA CI Daily Status:* all jobs passing{{else}}:red_circle: *ROSA CI Daily Status:* failures detected{{end}} (<{{.Status.URL}}|Full report>)
      <https://prow.ci.openshift.org/?type=periodic&job=*rosa-e2e-main-periodics-rosa-hcp-e2e*|ROSA HCP E2E> | <https://prow.ci.openshift.org/?type=periodic&job=*rosa-e2e-main-periodics-rosa-classic-sts-e2e*|ROSA STS E2E> | <https://prow.ci.openshift.org/?type=periodic&job=*rosa-e2e-main-periodics-osd-gcp-e2e*|OSD GCP E2E> | <https://prow.ci.openshift.org/?type=periodic&job=*ocm-fvt*rosa*|OCM FVT> | <https://prow.ci.openshift.org/?type=periodic&job=*main-nightly-*e2e-rosa-hcp-ovn|HCP CONF> | <https://prow.ci.openshift.org/?type=periodic&job=*main-nightly-*e2e-rosa-sts-ovn|STS CONF> | <https://prow.ci.openshift.org/?type=periodic&job=*periodic-ci-openshift-online-rosa-gap-analysis-main-periodics-nightly*|ROSA GAP ANALYSIS>
      :bar_chart: <https://sippy.dptools.openshift.org/sippy-ng/release/rosa-stage|Sippy>
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-e2e
