base_images:
  nested-podman:
    name: nested-podman
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.26-openshift-4.23
images:
  items:
  - dockerfile_literal: |
      FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-4.23
      RUN dnf install -y python3-pip && python3 -m pip install yamlpath
      RUN curl https://certs.corp.redhat.com/certs/Current-IT-Root-CAs.pem \
            -o /etc/pki/ca-trust/source/anchors/Current-IT-Root-CAs.pem && \
          update-ca-trust
    to: osdfm-release-tools
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ocm-fvt-periodic-osdfm-basic-periodic-integration
  capabilities:
  - intranet
  - nested-podman
  cron: 0 9 * * 1
  nested_podman: true
  restrict_network_access: false
  steps:
    env:
      OCM_FVT_JOB_NAME: osdfm-basic-periodic-integration
      OCM_FVT_OCM_ENV: integration
      OCM_FVT_REPORT_JIRA: "false"
      OCM_FVT_SERVICE: osdfm
    post:
    - ref: rosa-e2e-ocm-fvt-osdfm-int-to-stage-release
    test:
    - ref: rosa-e2e-ocm-fvt-longrunning
  timeout: 10h0m0s
- as: ocm-fvt-periodic-osdfm-mc-autoscaling-integration
  capabilities:
  - nested-podman
  cron: 0 10 * * 4
  nested_podman: true
  steps:
    env:
      OCM_FVT_JOB_NAME: osdfm-mc-autoscaling-integration
      OCM_FVT_OCM_ENV: integration
      OCM_FVT_REPORT_JIRA: "false"
      OCM_FVT_SERVICE: osdfm
    test:
    - ref: rosa-e2e-ocm-fvt-longrunning
  timeout: 12h0m0s
- as: ocm-fvt-periodic-osdfm-sc-autoscaling-integration
  capabilities:
  - nested-podman
  cron: 0 10 * * 3
  nested_podman: true
  steps:
    env:
      OCM_FVT_JOB_NAME: osdfm-sc-autoscaling-integration
      OCM_FVT_OCM_ENV: integration
      OCM_FVT_REPORT_JIRA: "false"
      OCM_FVT_SERVICE: osdfm
    test:
    - ref: rosa-e2e-ocm-fvt-longrunning
  timeout: 12h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-e2e
  variant: ocm-fvt-osdfm-integration
