build_root:
  project_image:
    dockerfile_path: ci/build-root/Dockerfile
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  commands: make lint
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: app-sre
  repo: infra
