{
 "title": "Boskos Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "Running Clusters by Platform",
   "type": "graph",
   "description": "sum(label_replace(boskos_resources{state=\"leased\"}, \"type\", \"$1\", \"type\", \"(.*)-quota-slice\")) by(type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(boskos_resources{state=\"leased\"}, \"type\", \"$1\", \"type\", \"(.*)-quota-slice\")) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "AWS Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCP Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCP-2 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"gcp-openshift-gce-devel-ci-2-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gcp-openshift-gce-devel-ci-2-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Azure Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "vSphere Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Packet.net Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack Kuryr Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-kuryr-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-kuryr-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack Vexxhost Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-vexxhost-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-vexxhost-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack VH Mecha Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-vh-mecha-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-vh-mecha-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}