{
 "title": "dptp dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "CI Operator Failure Rates by Reason",
   "type": "graph",
   "description": "sum(rate(ci_operator_error_rate{state=\"failed\",reason!=\"executing_graph:step_failed:utilizing_lease\",reason!=\"executing_graph:step_failed:running_pod\",reason!=\"executing_graph:step_failed:building_cache_image\",reason!=\"executing_graph:step_failed:building_image_from_source\",reason!=\"executing_graph:step_failed:building_project_image\",reason!=\"executing_graph:step_failed:cloning_source\",reason!=\"executing_graph:interrupted\"}[30m])) by (reason)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ci_operator_error_rate{state=\"failed\",reason!=\"executing_graph:step_failed:utilizing_lease\",reason!=\"executing_graph:step_failed:running_pod\",reason!=\"executing_graph:step_failed:building_cache_image\",reason!=\"executing_graph:step_failed:building_image_from_source\",reason!=\"executing_graph:step_failed:building_project_image\",reason!=\"executing_graph:step_failed:cloning_source\",reason!=\"executing_graph:interrupted\"}[30m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "IPI-Deprovision Failures",
   "type": "graph",
   "description": "rate(prowjob_state_transitions{job_name=\"periodic-ipi-deprovision\",state=\"failure\"}[30m])",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prowjob_state_transitions{job_name=\"periodic-ipi-deprovision\",state=\"failure\"}[30m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Plank Infra-Jobs Failures",
   "type": "graph",
   "description": "sum(rate(prowjob_state_transitions{job=\"prow-controller-manager\",job_name!~\"rehearse.*\",state=\"failure\"}[5m])) by (job_name) * on (job_name) group_left prow_job_labels{job_agent=\"kubernetes\",label_ci_openshift_io_role=\"infra\"}",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"prow-controller-manager\",job_name!~\"rehearse.*\",state=\"failure\"}[5m])) by (job_name) * on (job_name) group_left prow_job_labels{job_agent=\"kubernetes\",label_ci_openshift_io_role=\"infra\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}