{
 "title": "jenkins-operator dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(resync_period_seconds_count, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "number of Prow jobs by type for job ${job}",
   "type": "graph",
   "description": "sum(prowjobs{job=\"${job}\"}) by (type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=\"${job}\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs by state for job ${job}",
   "type": "graph",
   "description": "sum(prowjobs{job=\"${job}\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=\"${job}\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "number of requests by verb for job ${job}",
   "type": "graph",
   "description": "sum(rate(jenkins_requests{job=\"${job}\"}[1m])) by (verb)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jenkins_requests{job=\"${job}\"}[1m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "number of requests by code for job ${job}",
   "type": "graph",
   "description": "sum(rate(jenkins_requests{job=\"${job}\"}[1m])) by (code)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jenkins_requests{job=\"${job}\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "median number of request reties for job ${job}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(jenkins_request_latency_bucket{job=\"${job}\"}[1m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(jenkins_request_latency_bucket{job=\"${job}\"}[1m])) by (le))",
     "legendFormat": "${job}"
    }
   ]
  },
  {
   "title": "median resync period for job ${job}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(resync_period_seconds_bucket{job=\"${job}\"}[1m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(resync_period_seconds_bucket{job=\"${job}\"}[1m])) by (le))",
     "legendFormat": "${job}"
    }
   ]
  }
 ]
}