{
 "title": "prow dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "up",
   "type": "graph",
   "description": "sum by(job) (up)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(job) (up)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=\"ci\",container_name!=\"POD\"} * on (pod) group_left(label_component) kube_pod_labels{pod!=\"\",label_app=\"prow\"}) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "description": "CPU Request Saturation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod)(pod:container_cpu_usage:sum{namespace=\"ci\",container_name!=\"POD\"} * on (pod) group_left() kube_pod_labels{pod!=\"\",label_app=\"prow\"})/ sum(kube_pod_container_resource_requests_cpu_cores) by (pod)) > 1.5",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"ci\",container!=\"POD\",container!=\"\"} * on (pod) group_left(label_component) kube_pod_labels{pod!=\"\",label_app=\"prow\"}) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Memory Request Saturation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod)(container_memory_working_set_bytes{namespace=\"ci\",container!=\"POD\",container!=\"\"} * on (pod) group_left() kube_pod_labels{pod!=\"\",label_app=\"prow\"})/ sum(kube_pod_container_resource_requests_memory_bytes) by (pod)) > 1.5",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ephemeral storage",
   "type": "graph",
   "description": "Ephemeral storage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_fs_usage_bytes:sum{namespace=\"ci\",container_name!=\"POD\"} * on (pod) group_left(label_component) kube_pod_labels{pod!=\"\",label_app=\"prow\"}) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  }
 ]
}