base_images:
  ansible:
    name: "4.18"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.18"
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.19"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.18"
  tools:
    name: "4.18"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.18"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.18"
  target:
    release:
      architecture: amd64
      channel: candidate
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: azure-ipi-disc-oidc-oc-mirror-f28
  cron: 51 13 12 * *
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      EXTRACT_MANIFEST_INCLUDED: "true"
      MIRROR_BIN: oc-mirror
      MIRROR_GRAPH_DATA: "true"
    test:
    - ref: cucushift-upgrade-mirror-images-by-oc-mirror
    - ref: cucushift-upgrade-prehealthcheck
    - ref: cucushift-upgrade-toimage
    - ref: cucushift-upgrade-healthcheck
    workflow: cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: ota-amd64-stable-4.19-upgrade-from-stable-4.18
