base_images:
  ansible:
    name: "4.18"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.18"
    namespace: ocp
    tag: openstack-installer
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.18"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.18"
  tools:
    name: "4.18"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.18"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
releases:
  intermediate1:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.18"
  intermediate2:
    release:
      architecture: multi
      channel: candidate
      version: "4.19"
  latest:
    candidate:
      architecture: multi
      product: ocp
      relative: 1
      stream: nightly
      version: "4.18"
  target:
    release:
      architecture: multi
      channel: candidate
      version: "4.18"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: baremetal-ipi-ovn-ipv4-fips-vmedia-amd-f28
  capabilities:
  - intranet
  cron: 33 14 13 * *
  steps:
    cluster_profile: equinix-ocp-metal-qe
    env:
      AUX_HOST: openshift-qe-metal-ci.arm.eng.rdu2.redhat.com
      ENABLE_OTA_TEST: OCP-25473
      FIPS_ENABLED: "true"
      RESERVE_BOOTSTRAP: "false"
      architecture: amd64
      masters: "3"
      workers: "2"
    test:
    - as: set-upgrade-releases
      commands: echo "${INTERMEDIATE_RETARGET}" > ${SHARED_DIR}/upgrade-edge
      dependencies:
      - env: INTERMEDIATE_RETARGET
        name: release:intermediate1
      from: cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - chain: openshift-upgrade-qe-test
    workflow: baremetal-lab-ipi-virtual-media
- as: gcp-ipi-confidential-computing-fips-f28
  cron: 9 20 22 * *
  steps:
    cluster_profile: gcp-qe
    env:
      ENABLE_OTA_TEST: OCP-25473
      FIPS_ENABLED: "true"
    test:
    - as: set-upgrade-releases
      commands: echo "${INTERMEDIATE_RETARGET}" > ${SHARED_DIR}/upgrade-edge
      dependencies:
      - env: INTERMEDIATE_RETARGET
        name: release:intermediate2
      from: cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-gcp-ipi-confidential-computing
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: ota-multi-stable-4.18-upgrade-from-stable-4.18
