additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: gcp.ci.openshift.org
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: build02
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: openshift-ci-build-farm
    region: us-central1
publish: External
pullSecret: '{{ pull_secret }}'
sshKey: '{{ ssh_key }}'
