approve:
- commandHelpLink: ""
  repos:
  - openshift/agentic-skills
  require_self_approval: false
lgtm:
- repos:
  - openshift/agentic-skills
  review_acts_as_lgtm: true
plugins:
  openshift/agentic-skills:
    plugins:
    - approve
