approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  repos:
  - openshift-priv/cluster-control-plane-machine-set-operator
  require_self_approval: true
lgtm:
- repos:
  - openshift-priv/cluster-control-plane-machine-set-operator
plugins:
  openshift-priv/cluster-control-plane-machine-set-operator:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - size
    - skip
    - trigger
    - verify-owners
    - wip
    - yuks
