apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox
  namespace: ci
spec:
  jobName: blackbox
  module: http_2xx
  prober:
    url: blackbox-prober.ci.svc
    path: /probe
  targets:
    staticConfig:
      static:
      - https://steps.ci.openshift.org
      - https://amd64.ocp.releases.ci.openshift.org
      - https://arm64.ocp.releases.ci.openshift.org
      - https://ppc64le.ocp.releases.ci.openshift.org
      - https://s390x.ocp.releases.ci.openshift.org
      - https://multi.ocp.releases.ci.openshift.org
      - https://amd64.origin.releases.ci.openshift.org
      - https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com
      - https://console.build01.ci.openshift.org
      - https://console.build02.ci.openshift.org
      - https://console-openshift-console.apps.build03.ci.devcluster.openshift.com
      - https://console.build04.ci.openshift.org
      - https://console-openshift-console.apps.build05.ci.devcluster.openshift.com
      - https://console-openshift-console.apps.build06.ci.devcluster.openshift.com
      - https://console-openshift-console.apps.build07.ci.devcluster.openshift.com
      - https://console.build08.ci.openshift.org
      - https://console-openshift-console.apps.build09.ci.devcluster.openshift.com
      - https://console-openshift-console.apps.build10.ci.devcluster.openshift.com
      - https://console-openshift-console.apps.build11.ci.devcluster.openshift.com
      - https://console.core.ci.openshift.org
      - https://console-openshift-console.apps.hosted-mgmt.ci.devcluster.openshift.com
      - https://console-openshift-console.apps.build02.vmc.ci.openshift.org
      - https://hook-apps-ci.apps.ci.l2s4.p1.openshiftapps.com
      - https://quay-proxy.ci.openshift.org/healthz
      - https://selfservice.vault.ci.openshift.org/ping
      - https://pr-payload-tests.ci.openshift.org/readyz
      - https://docs.ci.openshift.org
      - https://cluster-display.ci.openshift.org/api/health
      - https://idp.ci.openshift.org/.well-known/openid-configuration
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-lenient
  namespace: ci
spec:
  jobName: blackbox-lenient
  module: http_2xx
  prober:
    url: blackbox-prober.ci.svc
    path: /probe
  targets:
    staticConfig:
      static:
      - https://prow.ci.openshift.org
