plugins:
  stolostron/clusterclaims-controller:
    plugins:
    - dco
triggers:
- org_invite:
    prominent: {}
  repos:
  - stolostron/clusterclaims-controller
  trusted_apps:
  - red-hat-konflux
  - openshift-merge-bot
