base_images:
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.22"
  upi-installer:
    name: "4.21"
    namespace: ocp
    tag: upi-installer
prowgen:
  disable_sparse_checkout: true
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.21"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: azure-ipi-kata
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      CUSTOM_AZURE_REGION: eastus
      ENABLE_MUST_GATHER: "true"
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
    workflow: sandboxed-containers-operator-e2e-azure
  timeout: 24h0m0s
- as: azure-ipi-peerpods
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      CUSTOM_AZURE_REGION: eastus
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
      WORKLOAD_TO_TEST: peer-pods
    workflow: sandboxed-containers-operator-e2e-azure
  timeout: 24h0m0s
- as: azure-ipi-coco
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: true
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      CUSTOM_AZURE_REGION: eastus
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      INITDATA: H4sICJdaD2oAA2luaXRkYXRhLnRvbWwA7VhZc6M4F33nV7h4yXzltg3enap+AIN3wCzxQiqVkkEsNpuRMMZd+e8jnExPpqedzMPM99SkHIzu0T33XklHwiBw49THXlj5WqGRB5qdLk2dYIr8OCqbmDpbZ2iKerQBBk8UDUAdx2FAE9vd3R31iOMDjJ6tOHJ8Fz398Fy3Yit+BqQ9S4PSm4dxct9oHHaohmB68i1Yw2mGMIS1OIEpwHFaQwV5DusgSVCdGJsdpsMO6uCSpbCOQGTv4jO0CQEGfkTiJBxhGd9fiQnDf09qwRSXBDRdKy9eHE/lylDUjOloOuQM8dpKSdOpIAjDIefoLpdPec4lH4OTefdw9A7+eJAzPKeiESdwoaSr+dTdCitVFQQeJ7vQLihzI18W60FubmaePR4UqiC25MuhkAyJlYxtPvEsWdpvc9kQO5JhsYogNdfXNrdsa1Nvja31/ucMnxFQriv6EseMh/pxrE93LUEVScgPHNee8kLO5cQ+52KSljrsue6x1RfOvUYBx5rUljVWDilzsCzc7NCPFS/MmLUqVp28L22HjteT+vG+L/YPS840D+teDy6W/Fbq2M4lAZLnrXSYsXtKKcRFw5BGawRlzqj2FUu5JJcmP1OsXjXN8fwsa43zVndH65HbxOxlNH8QmqrSWiSbaiPtU4BnOsgu8uGsP12N9Ifc3LV2zVkEhhlcm5u+xRpKdxBkzo4J5rO5HLH8Ikj2u+pg1IGsfKRERmdVcbydj5nJ3BycDE9dGafsDMzqqAG1ERN7y6y7VvNue9vZdApDaR5mUZ9x5W0A9uaZWlSPi0V4ydFITGQ0OGsSwyp802ssmmfVmJu+2YJaocs2yh1lle/MfaT1+q0qy9vmfDOXKc6VeI4b7zWDFySuPebYB1vIRb6RqyKZWMNE4HTelVcTjeCcvjgUuDGnThqcK3ISz4ypawdXXfO81uqmUbHgoq6XVYWJOpPOWo956LqSIfxkZnLKkCMc1KRR4P26uXDXHTZcKIuLMVnAaCibK41pDTRl3mjGjsVpg027U5XRoghFydn5AhI9yz+FRwptwjjedp0GHJudWe7unH64EZcAZIX+4I43ZidbXyYLfKie4WXB7bGqQLc9FpvWJDfN45RifWY6Yly161djxyia4fw8nm30dNSKq0bQ38jLhzZj7AcZO6oedacqB/oxXeCBa/jHA2N6lDUbzNoRKcgw0xRtuww5hc23g+Z5s9kZ7Us7umw7XRNnl+3q5HnalvVnY8Xgtr3lEFx2qk0Fw+OGWYPF0tpO2mwb5fI8XbdM9xxM4mgVtYdutDr11gbQ2Ja6a9oF4E94PrE7rn5Za72Q8vpK22jKW85WkWc9FOfDbNvMv36lrnIhysLfJIQIDFWKLUVbtvcmv2/6i2LrAEsRussi/0xUrpFmUeOqgjaMsA+C2p+q1Si7lz3uKCuFb3ZEOj8+EQE97KwnKgIhLCXNsp7JM/2fSyjx+PxLRn/J6C8Z/SWj/w8ZpR79ELjwibrenhG0MnL6LZ6TOPCtotTRb7QNHZAFmL5//EbjIoH0PZ3CPbQw/fL0hcYpiFASpxjR9wRb6m9afnM9K6378U3txRDhP59rV/5ait6zIHJyJUoKdd+NoE1/oQ+wWALsERPRyVLc30IjJAQb1YgdNci/GkNCe3l5uXvbJl6zqafQjf84qCfAOhDGCvlE+C1dilShzKTiZLhUaeIpj1Mb1f3opsW5ZYHkpYF4fIuwwtk2py1l6LveLk6RBo8ZKUDl/muF7A3wPUzPQXLLPAxiBHVs+9FNRJwUIz+AN+0pBBgO/6j7xzD9dZu6BRJIYxoXn6DGEEsQp751M2mCUBRJPJGRuAkpWwVIgg5uuln4CE8jDFMHWPBDlBZn+DZCguEkxkmQuXyxTOPdzVoqUUBqOFw+kB63MEuQoc/LvcyCYFqugFsADQJbx2RQ3hM55LTyHhLGp8+pXmE6BgFc+Sn2YwfpHkihFGcRvlkTDSIIbY2MdBwK8PQBLAs/j0GH+HVAyRwz/PBm1uXCBwEZAzKeN0MjqaT4c8oSZaTA8iP3AwxG/8BTnHziyMDFulyiyL/czO0hsf/JQnyFiYkHQ3KuDD4epVfw9zXwMezjRbAGPv6k8OIZWn+H/HVSkpFeXrX1Jg/ZbuCNmU39hMF3Kt+oCrn8KMnwMzk0h2RSElEnW4kF8G90hf7yaqsnrz3rXOqi/137oJic5kEQxDm0v3f1o8qr/D+XP+nUfzCjn5F9/dEJ9UJR75yUKZRR0j86o+8rj1eH5UVb5dvE26sE2+zVGfLH3vcZplu+mTRSiOIsteD3XQ7gctMEZM1GtfKeocbrjf7yrzpNr8ucJj6fSGLlbvk7KYTL/xYTAAA=
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-3.rhaos4.19.el9
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 6h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: http://kbs-service-trustee-operator-system.apps.tru250519.azure.sandboxedcontainers.com
      WORKLOAD_TO_TEST: coco
    workflow: sandboxed-containers-operator-e2e-azure
  timeout: 24h0m0s
- as: aro-ipi-peerpods
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: "4.17"
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      HYPERSHIFT_AZURE_LOCATION: eastus
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      LOCATION: eastus
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
      WORKLOAD_TO_TEST: peer-pods
    workflow: sandboxed-containers-operator-e2e-aro
  timeout: 24h0m0s
- as: aro-ipi-coco
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: "4.17"
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      HYPERSHIFT_AZURE_LOCATION: eastus
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      LOCATION: eastus
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
      WORKLOAD_TO_TEST: coco
    workflow: sandboxed-containers-operator-e2e-aro
  timeout: 24h0m0s
- as: aws-ipi-peerpods
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: aws-sandboxed-containers-operator
    env:
      AWS_REGION_OVERRIDE: us-east-2
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
      WORKLOAD_TO_TEST: peer-pods
    workflow: sandboxed-containers-operator-e2e-aws
  timeout: 24h0m0s
- as: aws-ipi-coco
  capabilities:
  - intranet
  cron: 0 0 31 2 1
  reporter_config:
    channel: '#kata-ocp-ci-reports'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}}SUCCESS{{else}}ERROR{{end}}
      {{trimPrefix "periodic-ci-openshift-sandboxed-containers-operator-" .Spec.Job}}
      <{{.Status.URL}}|View logs>'
  restrict_network_access: false
  steps:
    cluster_profile: aws-sandboxed-containers-operator
    env:
      AWS_REGION_OVERRIDE: us-east-2
      CATALOG_SOURCE_IMAGE: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest
      CATALOG_SOURCE_NAME: brew-catalog
      ENABLE_MUST_GATHER: "true"
      ENABLEPEERPODS: "true"
      INITDATA: ""
      INSTALL_KATA_RPM: "true"
      KATA_RPM_VERSION: 3.31.0-2.rhaos4.19.el9
      MUST_GATHER_IMAGE: registry.redhat.io/openshift-sandboxed-containers/osc-must-gather-rhel9:latest
      MUST_GATHER_ON_FAILURE_ONLY: "false"
      RUNTIMECLASS: kata-remote
      SLEEP_DURATION: 0h
      TEST_FILTERS: ~DisconnectedOnly&;~Disruptive&;~C00133&
      TEST_RELEASE_TYPE: Pre-GA
      TEST_SCENARIOS: sig-kata.*Kata Author
      TEST_TIMEOUT: "90"
      TRUSTEE_URL: ""
      WORKLOAD_TO_TEST: coco
    workflow: sandboxed-containers-operator-e2e-aws
  timeout: 24h0m0s
zz_generated_metadata:
  branch: devel
  org: openshift
  repo: sandboxed-containers-operator
  variant: downstream-candidate421
