#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail

echo "=== Windows BYOH Provisioning with terraform-windows-provisioner ==="

# Debug: Print environment variables
echo "DEBUG: SHARED_DIR=${SHARED_DIR}"
echo "DEBUG: CLUSTER_PROFILE_DIR=${CLUSTER_PROFILE_DIR}"
echo "DEBUG: ARTIFACT_DIR=${ARTIFACT_DIR:-not set}"

# Test: Write a marker file to SHARED_DIR to verify it's actually shared
echo "Testing if SHARED_DIR is shared between steps..."
echo "provision-marker-$(date +%s)" > "${SHARED_DIR}/test-shared-dir-marker.txt"
echo "Wrote test marker to ${SHARED_DIR}/test-shared-dir-marker.txt"
shopt -s nullglob
files=("${SHARED_DIR}"/*test-shared* "${SHARED_DIR}"/*byoh*)
if [[ ${#files[@]} -gt 0 ]]; then
    for file in "${files[@]}"; do
        echo "Found: $(basename "$file")"
    done
else
    echo "No test files visible yet"
fi

# Write debug info to artifact directory for inspection
cat > "${ARTIFACT_DIR}/provision-debug-env.txt" <<EOF
SHARED_DIR=${SHARED_DIR}
CLUSTER_PROFILE_DIR=${CLUSTER_PROFILE_DIR}
ARTIFACT_DIR=${ARTIFACT_DIR:-not set}
BYOH_TMP_DIR will be: ${SHARED_DIR}/terraform_byoh/

Directory listings:
==================
ls -la ${SHARED_DIR}:
$(ls -la "${SHARED_DIR}" 2>&1 || echo "Directory does not exist or not accessible")

ls -la ${CLUSTER_PROFILE_DIR}:
$(ls -la "${CLUSTER_PROFILE_DIR}" 2>&1 || echo "Directory does not exist or not accessible")
EOF
echo "Debug info written to ${ARTIFACT_DIR}/provision-debug-env.txt"

# Generate unique suffix using 3 random alphanumeric characters (0-9, a-z)
# Windows NetBIOS limit: base name ≤ 8 chars (VM name will be base + "-<index>")
# "byoh-" (5 chars) + 3 alphanumeric chars = 8 chars (within limit)
# 36^3 = 46,656 possibilities for collision avoidance
CHARS="0123456789abcdefghijklmnopqrstuvwxyz"
UNIQUE_SUFFIX=""
UNIQUE_SUFFIX+=${CHARS:$((RANDOM % 36)):1}
UNIQUE_SUFFIX+=${CHARS:$((RANDOM % 36)):1}
UNIQUE_SUFFIX+=${CHARS:$((RANDOM % 36)):1}
export BYOH_INSTANCE_NAME="${BYOH_INSTANCE_NAME:-byoh-${UNIQUE_SUFFIX}}"
export BYOH_NUM_WORKERS="${BYOH_NUM_WORKERS:-2}"
export BYOH_WINDOWS_VERSION="${BYOH_WINDOWS_VERSION:-2022}"
# Use ARTIFACT_DIR for terraform (artifacts preserved for debugging)
export BYOH_TMP_DIR="${ARTIFACT_DIR}/terraform_byoh/"

echo "Using unique instance name: ${BYOH_INSTANCE_NAME}"

# Save instance name to SHARED_DIR for destroy step
echo "${BYOH_INSTANCE_NAME}" > "${SHARED_DIR}/byoh_instance_name.txt"
echo "Saved instance name to ${SHARED_DIR}/byoh_instance_name.txt"

# Windows credentials
# WINC_ADMIN_PASSWORD will be auto-generated by byoh.sh if not provided
# WINC_SSH_PUBLIC_KEY must be provided - extract from cluster profile
if [[ -f "${CLUSTER_PROFILE_DIR}/ssh-publickey" ]]; then
    WINC_SSH_PUBLIC_KEY=$(cat "${CLUSTER_PROFILE_DIR}/ssh-publickey")
    export WINC_SSH_PUBLIC_KEY
    echo "SSH public key loaded from cluster profile"
else
    echo "ERROR: ${CLUSTER_PROFILE_DIR}/ssh-publickey not found"
    exit 1
fi

# Load AWS Windows AMI if discovered by previous step (for UPI workflows)
if [[ -f "${SHARED_DIR}/AWS_WINDOWS_AMI" ]]; then
    AWS_WINDOWS_AMI=$(cat "${SHARED_DIR}/AWS_WINDOWS_AMI")
    export AWS_WINDOWS_AMI
    echo "Using Windows AMI from SHARED_DIR: ${AWS_WINDOWS_AMI}"
elif [[ -n "${AWS_WINDOWS_AMI:-}" ]]; then
    echo "Using Windows AMI from environment: ${AWS_WINDOWS_AMI}"
else
    echo "No AWS_WINDOWS_AMI specified - byoh.sh will attempt auto-discovery"
fi

# Load AWS region if discovered by previous step (for UPI workflows)
# Write to byoh.sh config file instead of relying on environment variables
if [[ -f "${SHARED_DIR}/AWS_REGION" ]]; then
    AWS_REGION=$(cat "${SHARED_DIR}/AWS_REGION")
    export AWS_REGION
    export AWS_DEFAULT_REGION="${AWS_REGION}"

    # Write to byoh.sh user config file (more reliable than env vars)
    mkdir -p "${HOME}/.config/byoh-provisioner"
    echo "# AWS region for UPI provisioning (auto-generated by windows-byoh-provision step)" > "${HOME}/.config/byoh-provisioner/config"
    echo "AWS_DEFAULT_REGION=${AWS_REGION}" >> "${HOME}/.config/byoh-provisioner/config"
    echo "Using AWS region from SHARED_DIR: ${AWS_REGION}"
    echo "Wrote AWS_DEFAULT_REGION=${AWS_REGION} to byoh.sh config file"
elif [[ -n "${AWS_REGION:-}" ]]; then
    export AWS_DEFAULT_REGION="${AWS_REGION}"
    echo "Using AWS region from environment: ${AWS_REGION}"
else
    echo "No AWS_REGION specified - byoh.sh will attempt auto-discovery"
fi

# Export credentials from cluster profile (platform-agnostic)
# terraform-windows-provisioner will auto-detect platform and use appropriate credentials
if [[ -f "${CLUSTER_PROFILE_DIR}/.awscred" ]]; then
    export AWS_SHARED_CREDENTIALS_FILE="${CLUSTER_PROFILE_DIR}/.awscred"
    export AWS_PROFILE="default"
    echo "AWS credentials configured"
fi

if [[ -f "${CLUSTER_PROFILE_DIR}/osServicePrincipal.json" ]]; then
    ARM_CLIENT_ID=$(jq -r .clientId "${CLUSTER_PROFILE_DIR}/osServicePrincipal.json")
    ARM_CLIENT_SECRET=$(jq -r .clientSecret "${CLUSTER_PROFILE_DIR}/osServicePrincipal.json")
    ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId "${CLUSTER_PROFILE_DIR}/osServicePrincipal.json")
    ARM_TENANT_ID=$(jq -r .tenantId "${CLUSTER_PROFILE_DIR}/osServicePrincipal.json")
    export ARM_CLIENT_ID ARM_CLIENT_SECRET ARM_SUBSCRIPTION_ID ARM_TENANT_ID
    echo "Azure credentials configured"
fi

if [[ -f "${CLUSTER_PROFILE_DIR}/gce.json" ]]; then
    GOOGLE_CREDENTIALS=$(cat "${CLUSTER_PROFILE_DIR}/gce.json")
    export GOOGLE_CREDENTIALS
    echo "GCP credentials configured"
fi

# Verify terraform and byoh.sh are available (pre-installed in terraform-windows-provisioner image)
if ! command -v terraform &> /dev/null; then
    echo "ERROR: terraform command not found in terraform-windows-provisioner image"
    exit 1
fi
if ! command -v byoh.sh &> /dev/null; then
    echo "ERROR: byoh.sh command not found in terraform-windows-provisioner image"
    exit 1
fi
terraform version -no-color
echo "Terraform and byoh.sh found in image"

# Debug: Verify AWS environment variables are set before calling byoh.sh
echo "DEBUG: Environment variables before calling byoh.sh:"
echo "  AWS_REGION=${AWS_REGION:-NOT_SET}"
echo "  AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-NOT_SET}"
echo "  AWS_WINDOWS_AMI=${AWS_WINDOWS_AMI:-NOT_SET}"

# Change to provisioner directory (scripts and configs are pre-installed in image)
cd /usr/local/share/byoh-provisioner

# WORKAROUND: For UPI, override platform detection to use "none" instead of "aws"
# UPI AWS clusters have platform:aws in install-config.yaml but are installed as platform=none
# Infrastructure CR reports AWS, causing byoh.sh to use AWS IPI code path (requires MachineSets)
# AWS_REGION file exists only in UPI workflows (created by aws-windows-ami-discover step)
if [[ -f "${SHARED_DIR}/AWS_REGION" ]]; then
    echo "Detected UPI workflow (AWS_REGION file exists from ami-discover step)"
    echo "Overriding byoh.sh platform detection to use 'none' for UPI..."

    # Get worker node InternalDNS (correct AWS FQDN for all regions)
    WORKER_INTERNAL_DNS=$(oc get nodes -l "node-role.kubernetes.io/worker" -o=jsonpath="{.items[0].status.addresses[?(@.type=='InternalDNS')].address}")
    echo "Worker InternalDNS: ${WORKER_INTERNAL_DNS}"

    # Store the real oc location before modifying PATH
    REAL_OC=$(which oc)
    echo "Real oc location: ${REAL_OC}"

    # Create a wrapper oc command that:
    # 1. Returns "None" for platform detection
    # 2. Returns InternalDNS for hostname queries (correct AWS FQDN for all regions)
    cat > /tmp/oc << EOF
#!/bin/bash
# Log all commands for debugging
echo "[OC-WRAPPER] Command: \$*" >> /tmp/oc-wrapper-debug.log

# Wrapper to force platform detection to return "none" for UPI
if [[ "\$*" == *"infrastructure cluster"* ]] && [[ "\$*" == *"platformStatus.type"* ]]; then
    echo "[OC-WRAPPER] Matched: platform detection" >> /tmp/oc-wrapper-debug.log
    echo "None"
elif [[ "\$*" == *"status.addresses"* ]] && [[ "\$*" == *"Hostname"* ]]; then
    echo "[OC-WRAPPER] Matched: hostname query" >> /tmp/oc-wrapper-debug.log
    # Return InternalDNS instead of Hostname (correct AWS FQDN for all regions)
    echo "${WORKER_INTERNAL_DNS}"
else
    echo "[OC-WRAPPER] No match, passing through to real oc" >> /tmp/oc-wrapper-debug.log
    exec "${REAL_OC}" "\$@"
fi
EOF
    chmod +x /tmp/oc

    # Prepend /tmp to PATH so our wrapper is found first
    export PATH="/tmp:${PATH}"

    echo "Platform override applied - oc wrapper will return:"
    echo "  - platform='none' for platform detection"
    echo "  - hostname='${WORKER_INTERNAL_DNS}' for hostname queries (InternalDNS)"

    # Set trap to dump debug log on exit (success or failure)
    trap 'echo "=== OC WRAPPER DEBUG LOG ==="; cat /tmp/oc-wrapper-debug.log 2>/dev/null || echo "No debug log found"' EXIT
fi

echo "Provisioning ${BYOH_NUM_WORKERS} Windows ${BYOH_WINDOWS_VERSION} nodes..."
./byoh.sh apply "${BYOH_INSTANCE_NAME}" "${BYOH_NUM_WORKERS}" "" "${BYOH_WINDOWS_VERSION}"

# Wait for BYOH nodes specifically to be Ready (identified by WMCO label)
# Default timeout: 45 minutes (vSphere provisioning takes longer than cloud platforms)
READY_TIMEOUT="${BYOH_READY_TIMEOUT:-45m}"
echo "Waiting for ${BYOH_NUM_WORKERS} BYOH Windows nodes to become Ready (timeout: ${READY_TIMEOUT})..."
timeout "${READY_TIMEOUT}" bash -c '
    loops=0
    max_loops=30
    sleep_seconds=60
    while (( loops < max_loops )); do
        # Count nodes where STATUS field (column 2) starts with "Ready" (not "NotReady")
        READY=$(oc get nodes -l kubernetes.io/os=windows,windowsmachineconfig.openshift.io/byoh=true --no-headers 2>/dev/null | awk '\''$2 == "Ready" || $2 ~ /^Ready,/ {print}'\'' | wc -l)
        TOTAL=$(oc get nodes -l kubernetes.io/os=windows,windowsmachineconfig.openshift.io/byoh=true --no-headers 2>/dev/null | wc -l)
        echo "[$loops/$max_loops] BYOH nodes ready: ${READY}/${TOTAL} (waiting for '${BYOH_NUM_WORKERS}')"
        if [[ "${READY}" -ge "'${BYOH_NUM_WORKERS}'" ]]; then
            echo "All ${READY} BYOH Windows nodes are Ready"
            break
        fi
        ((loops++))
        sleep $sleep_seconds
    done
    if (( loops >= max_loops )); then
        echo "Timeout: Only ${READY}/'${BYOH_NUM_WORKERS}' BYOH nodes became Ready after ${max_loops} attempts"
        oc get nodes -l kubernetes.io/os=windows,windowsmachineconfig.openshift.io/byoh=true -o wide || true
        exit 1
    fi
'

echo "Windows BYOH nodes provisioned successfully"
echo "All Windows nodes in cluster:"
oc get nodes -l kubernetes.io/os=windows -o wide
echo ""
echo "BYOH nodes specifically (labeled windowsmachineconfig.openshift.io/byoh=true):"
oc get nodes -l kubernetes.io/os=windows,windowsmachineconfig.openshift.io/byoh=true -o wide

# Export instance information for WMCO BYOH e2e tests
echo "Exporting Windows instance information to SHARED_DIR for WMCO tests..."

# Detect platform
PLATFORM=$(oc get infrastructure cluster -o=jsonpath="{.status.platformStatus.type}" | tr '[:upper:]' '[:lower:]')

# Get instance IPs from Terraform output
TERRAFORM_DIR="${BYOH_TMP_DIR}${PLATFORM}"
if [[ ! -d "${TERRAFORM_DIR}" ]]; then
    echo "ERROR: Terraform directory not found: ${TERRAFORM_DIR}"
    exit 1
fi

cd /usr/local/share/byoh-provisioner
INSTANCE_IPS=$(terraform -chdir="${TERRAFORM_DIR}" output -json instance_ip 2>/dev/null | jq -r '.[]' || echo "")

if [[ -z "${INSTANCE_IPS}" ]]; then
    echo "WARNING: No instance IPs found in Terraform output"
    # Fallback: get from node IPs
    INSTANCE_IPS=$(oc get nodes -l kubernetes.io/os=windows -o jsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}')
fi

# Determine username based on platform
case "${PLATFORM}" in
    azure)
        USERNAME="capi"
        ;;
    *)
        USERNAME="Administrator"
        ;;
esac

# Write instance files in WMCO BYOH format
# Format: ${SHARED_DIR}/<ip>_windows_instance.txt containing "username: <username>"
# Read into array to handle empty values and special characters properly
IFS=' ' read -r -a IP_ARRAY <<< "${INSTANCE_IPS}"
for ip in "${IP_ARRAY[@]}"; do
    [[ -z "$ip" ]] && continue  # Skip empty values
    instance_file="${SHARED_DIR}/${ip}_windows_instance.txt"
    cat > "${instance_file}" <<EOF
username: ${USERNAME}
EOF
    echo "Created instance file: ${instance_file}"
done

echo "Instance information exported for WMCO BYOH tests"

# Save terraform state + config to SHARED_DIR for destroy step
# Tar directory excluding .terraform/ (providers) to avoid 3MB Secret limit
echo "Saving terraform state and config to SHARED_DIR for destroy step..."
PLATFORM=$(oc get infrastructure cluster -o=jsonpath="{.status.platformStatus.type}" | tr '[:upper:]' '[:lower:]')
if [[ -d "${ARTIFACT_DIR}/terraform_byoh/${PLATFORM}" ]]; then
    tar -cf "${SHARED_DIR}/terraform_byoh_${PLATFORM}.tar" -C "${ARTIFACT_DIR}/terraform_byoh/${PLATFORM}" --exclude='.terraform' .
    echo "Terraform files saved to ${SHARED_DIR}/terraform_byoh_${PLATFORM}.tar"
    ls -lh "${SHARED_DIR}/terraform_byoh_${PLATFORM}.tar"
else
    echo "WARNING: Terraform directory not found at ${ARTIFACT_DIR}/terraform_byoh/${PLATFORM}/"
fi

echo "=== Windows BYOH Provisioning Complete ==="
