approve:
- commandHelpLink: ""
  repos:
  - openshift-priv/velero-plugin-for-csi
  require_self_approval: false
lgtm:
- repos:
  - openshift-priv/velero-plugin-for-csi
plugins:
  openshift-priv/velero-plugin-for-csi:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - wip
    - yuks
