#!/bin/sh

set -euo pipefail

# Creates a new release branch for FROM, then creates a new commit into master and
# tags it as TO, then pushes both to upstream.
#
# Usage: TO= FROM= ./branch [tag|reset|push]
#
# Argument:
# * <empty>: displays latest commit on the branch
# * tag:     creates the tags and branches locally
# * reset:   deletes the branches or tags to start over
# * push:    actually push the branches and tags

base=$( dirname "${BASH_SOURCE[0]}")
source "${base}/lib/constants.sh"

DIR=${DIR:-/tmp/dist}
BRANCH=${BRANCH:-master}

for repo in `managed_repos "${BRANCH}"`; do
  if [[ ! -d ${DIR}/src/github.com/${repo} ]]; then
    mkdir -p ${DIR}/src/github.com/${repo}
    pushd ${DIR}/src/github.com/${repo} &>/dev/null
    git clone --depth=1 --branch ${BRANCH} git@github.com:${repo} .
    popd &>/dev/null
  fi
done

# create a commit in each repo
if [[ "${1-}" == "bump" ]]; then
  for repo in `managed_repos "${BRANCH}"`; do
    pushd ${DIR}/src/github.com/${repo} &>/dev/null
    git checkout ${BRANCH}
    git fetch origin ${BRANCH} 2>/dev/null
    git reset --hard origin/${BRANCH} >/dev/null
    echo date '+%Y%m%d-%H%M%S' > .repo-date; git add .repo-date; git commit -S -m "Updating branch ${BRANCH}"
    popd &>/dev/null
  done
  exit 0
fi

# clear the repos back to a known state
if [[ "${1-}" == "reset" ]]; then
  for repo in `managed_repos "${BRANCH}"`; do
    pushd ${DIR}/src/github.com/${repo} &>/dev/null
    git fetch origin ${BRANCH} 2>/dev/null
    git checkout ${BRANCH}
    git reset origin/${BRANCH} --hard >/dev/null
    if [[ -n "${FROM-}" ]]; then
      git branch -D release-${FROM} || true
      git tag -d v${FROM}.0-rc.0 || true
    fi
    if [[ -n "${TO-}" ]]; then
      git tag -d v${TO}.0-alpha.0 || true
    fi
    popd &>/dev/null
  done
  exit 0
fi

if [[ -z "${FROM-}" ]]; then
	echo "Must set FROM= to the major/minor version of the current release, e.g. 3.9"
  exit 1
fi
if [[ -z "${TO-}" ]]; then
  echo "Must set TO= to the major/minor version of the next release, e.g. 3.10"
  exit 1
fi

for repo in `managed_repos "${BRANCH}"`; do
  pushd ${DIR}/src/github.com/${repo} &>/dev/null

  if [[ "${1-}" == "" ]]; then
    echo ${repo} '|' $( git log --oneline -1 HEAD )
    continue
  fi

  if [[ "${1-}" == "create" ]]; then
    if ! git rev-parse release-${FROM} &>/dev/null; then
      git checkout -b release-${FROM} ${BRANCH}
    fi
    git push origin "release-${FROM}"
    continue
  fi

  if git rev-parse release-${FROM} &>/dev/null; then
    echo "release-${FROM} branch already exists" 2>&1
    continue
  fi
  git checkout -b release-${FROM} ${BRANCH}
  git checkout ${BRANCH}

  ! git rev-parse v${TO}.0-rc.0 &>/dev/null
  git tag -f -s -a -m "v${FROM}.0-rc.0" v${FROM}.0-rc.0
  echo ${TO} > .release; git add .release; git commit -S -m "Branch for v${TO}"

  ! git rev-parse v${TO}.0-alpha.0 &>/dev/null
  git tag -f -s -a -m "v${TO}.0-alpha.0" v${TO}.0-alpha.0

  if [[ "${1-}" == "push" ]]; then
    git push origin "release-${FROM}" "v${TO}.0-alpha.0" "v${FROM}.0-rc.0" "${BRANCH}"
  fi

  popd &>/dev/null
done

