approve:
- repos:
  - openshift-priv/cluster-api-provider-openshift-assisted
  require_self_approval: false
lgtm:
- repos:
  - openshift-priv/cluster-api-provider-openshift-assisted
  review_acts_as_lgtm: true
plugins:
  openshift-priv/cluster-api-provider-openshift-assisted:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - retitle
    - shrug
    - size
    - skip
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift-priv/cluster-api-provider-openshift-assisted
  trusted_apps:
  - openshift-merge-bot
