apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=confirm
    openshift.io/description: ROSA cluster lease inventory state management
    openshift.io/display-name: ROSA Cluster Lease
  name: rosa-cluster-lease
