approve:
- repos:
  - openshift/azure-kubernetes-kms
  require_self_approval: false
label:
  restricted_labels:
    openshift/azure-kubernetes-kms:
    - allowed_users:
      - bryan-cox
      - muraee
      label: backport-risk-assessed
lgtm:
- repos:
  - openshift/azure-kubernetes-kms
  review_acts_as_lgtm: true
plugins:
  openshift/azure-kubernetes-kms:
    plugins:
    - approve
