base_images:
  assisted-service-scripts:
    name: ocm-2.17
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  hypershift-tests:
    name: hypershift-tests
    namespace: hypershift
    tag: latest
  test-bin:
    name: "4.22"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.22"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.22"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-kubevirt-metal-ovn-backuprestore
  capabilities:
  - intranet
  cron: 0 6 * * 0
  steps:
    cluster_profile: equinix-ocp-hcp
    env:
      HYPERSHIFT_NODE_COUNT: "2"
      KONFLUX_DEPLOY_CATALOG_SOURCE: "true"
      KONFLUX_DEPLOY_OPERATORS: "true"
      KONFLUX_DEPLOY_SUBSCRIPTION: "false"
      KONFLUX_TARGET_FBC_TAGS: ocp__4.22__metallb-rhel9-operator,ocp__4.22__ose-local-storage-rhel9-operator,oadp-operator-fbc-1.6.0-20260327171703
      KONFLUX_TARGET_OPERATORS: ""
      LOCAL_STORAGE_OPERATOR_SUB_SOURCE: ocp--4.22--ose-local-storage-rhel9-operator-konflux
      LVM_OPERATOR_SUB_CHANNEL: stable-4.22
      LVM_OPERATOR_SUB_SOURCE: lvm-catalogsource
      MCE_VERSION: "2.17"
      METALLB_OPERATOR_SUB_SOURCE: ocp--4.22--metallb-rhel9-operator-konflux
      OADP_OPERATOR_SUB_CHANNEL: stable
      OADP_OPERATOR_SUB_SOURCE: oadp-operator-fbc-1.6.0-20260327171703-konflux
      ODF_OPERATOR_SUB_CHANNEL: stable-4.21
      ODF_OPERATOR_SUB_SOURCE: redhat-operators-v4-21
      REDHAT_OPERATORS_INDEX_TAG: v4.21
    workflow: hypershift-mce-kubevirt-baremetalds-backuprestore
zz_generated_metadata:
  branch: backup_restore_kubevirt
  org: mgencur
  repo: hypershift
  variant: periodics
