{
 "title": "ci-chat-bot dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Time to Auth-Ready in minutes",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(ci_chat_bot_rosa_ready_duration_minutes_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ci_chat_bot_rosa_auth_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ci_chat_bot_rosa_auth_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ci_chat_bot_rosa_auth_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Time to Console-Ready in minutes",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(ci_chat_bot_rosa_console_duration_minutes_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ci_chat_bot_rosa_console_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ci_chat_bot_rosa_console_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ci_chat_bot_rosa_console_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Time to ROSA-Ready in minutes",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(ci_chat_bot_rosa_ready_duration_minutes_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ci_chat_bot_rosa_ready_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ci_chat_bot_rosa_ready_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ci_chat_bot_rosa_ready_duration_minutes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "ROSA Sync Time in seconds",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(ci_chat_bot_rosa_sync_duration_seconds_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ci_chat_bot_rosa_sync_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ci_chat_bot_rosa_sync_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ci_chat_bot_rosa_sync_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "ROSA Operation Error Rate",
   "type": "graph",
   "description": "sum(increase(cluster_bot_error_rate[${range}])) by (error)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cluster_bot_error_rate[${range}])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "ROSA Cluster Count",
   "type": "graph",
   "description": "Number of running ROSA clusters",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ci_chat_bot_rosa_cluster_count", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}