approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  repos:
  - openshift-kni/cnf-features-deploy
  require_self_approval: false
lgtm:
- repos:
  - openshift-kni/cnf-features-deploy
  review_acts_as_lgtm: true
triggers:
- repos:
  - openshift-kni/cnf-features-deploy
  trusted_apps:
  - red-hat-konflux
