base_images:
  claude-ai-helpers:
    name: claude-ai-helpers
    namespace: ci
    tag: latest
  hypershift-oadp-plugin:
    name: hypershift-oadp-plugin
    namespace: konveyor
    tag: hypershift-oadp-plugin
  kubevirt-datamover-controller:
    name: kubevirt-datamover-controller
    namespace: konveyor
    tag: oadp-dev
  kubevirt-datamover-plugin:
    name: kubevirt-datamover-plugin
    namespace: konveyor
    tag: oadp-dev
  kubevirt-velero-plugin:
    name: kubevirt-velero-plugin
    namespace: konveyor
    tag: kubevirt-velero-plugin
  oadp-cli:
    name: oadp-cli
    namespace: konveyor
    tag: oadp-cli
  oadp-must-gather:
    name: oadp-must-gather
    namespace: konveyor
    tag: oadp-must-gather
  oadp-non-admin:
    name: oadp-non-admin
    namespace: konveyor
    tag: oadp-non-admin
  oadp-vm-file-restore:
    name: oadp-vm-file-restore
    namespace: konveyor
    tag: oadp-dev
  oadp-vmdp:
    name: oadp-vmdp
    namespace: konveyor
    tag: oadp-vmdp
  oadp-vmfr-access:
    name: oadp-vmfr-access
    namespace: konveyor
    tag: oadp-dev
  oadp-vmfr-access-filebrowser:
    name: oadp-vmfr-access-filebrowser
    namespace: konveyor
    tag: oadp-dev
  oadp-vmfr-access-sshd:
    name: oadp-vmfr-access-sshd
    namespace: konveyor
    tag: oadp-dev
  openshift-velero-plugin:
    name: openshift-velero-plugin
    namespace: konveyor
    tag: openshift-velero-plugin
  tls-scanner-tool:
    name: "4.22"
    namespace: ocp
    tag: tls-scanner-tool
  velero:
    name: velero
    namespace: konveyor
    tag: velero
  velero-plugin-for-aws:
    name: velero-plugin-for-aws
    namespace: konveyor
    tag: velero-plugin-for-aws
  velero-plugin-for-gcp:
    name: velero-plugin-for-gcp
    namespace: konveyor
    tag: velero-plugin-for-gcp
  velero-plugin-for-legacy-aws:
    name: velero-plugin-for-legacy-aws
    namespace: konveyor
    tag: velero-plugin-for-legacy-aws
  velero-plugin-for-microsoft-azure:
    name: velero-plugin-for-microsoft-azure
    namespace: konveyor
    tag: velero-plugin-for-microsoft-azure
build_root:
  image_stream_tag:
    name: builder
    namespace: konveyor
    tag: ubi9-v1.26
images:
  items:
  - dockerfile_path: Dockerfile
    to: oadp-operator
  - dockerfile_path: build/ci-Dockerfile
    to: test-oadp-operator
operator:
  bundles:
  - dockerfile_path: build/Dockerfile.bundle
  substitutions:
  - pullspec: quay.io/konveyor/oadp-operator:latest
    with: oadp-operator
  - pullspec: quay.io/konveyor/hypershift-oadp-plugin:latest
    with: hypershift-oadp-plugin
  - pullspec: quay.io/konveyor/kubevirt-datamover-controller:latest
    with: kubevirt-datamover-controller
  - pullspec: quay.io/konveyor/kubevirt-datamover-plugin:latest
    with: kubevirt-datamover-plugin
  - pullspec: quay.io/konveyor/kubevirt-velero-plugin:latest
    with: kubevirt-velero-plugin
  - pullspec: quay.io/konveyor/oadp-cli-binaries:latest
    with: oadp-cli
  - pullspec: quay.io/konveyor/oadp-must-gather:latest
    with: oadp-must-gather
  - pullspec: quay.io/konveyor/oadp-non-admin:latest
    with: oadp-non-admin
  - pullspec: quay.io/konveyor/oadp-vm-file-restore:latest
    with: oadp-vm-file-restore
  - pullspec: quay.io/konveyor/oadp-vmdp-binaries:latest
    with: oadp-vmdp
  - pullspec: quay.io/konveyor/oadp-vmfr-access-filebrowser:latest
    with: oadp-vmfr-access-filebrowser
  - pullspec: quay.io/konveyor/oadp-vmfr-access-sshd:latest
    with: oadp-vmfr-access-sshd
  - pullspec: quay.io/konveyor/oadp-vmfr-access:latest
    with: oadp-vmfr-access
  - pullspec: quay.io/konveyor/openshift-velero-plugin:latest
    with: openshift-velero-plugin
  - pullspec: quay.io/konveyor/velero-plugin-for-aws:latest
    with: velero-plugin-for-aws
  - pullspec: quay.io/konveyor/velero-plugin-for-gcp:latest
    with: velero-plugin-for-gcp
  - pullspec: quay.io/konveyor/velero-plugin-for-legacy-aws:latest
    with: velero-plugin-for-legacy-aws
  - pullspec: quay.io/konveyor/velero-plugin-for-microsoft-azure:latest
    with: velero-plugin-for-microsoft-azure
  - pullspec: quay.io/konveyor/velero:latest
    with: velero
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 512Mi
tests:
- always_run: false
  as: e2e-test-cli-aws
  run_if_changed: .+\.go|go\.(\bmod\b|\bsum\b)|Makefile|Dockerfile|.dockerignore|.*\.ya{0,1}ml|build/.+|.sh
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OADP_BRANCH: oadp-dev
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      TEST_NAME: e2e-test-cli-aws
    post:
    - ref: oadp-analyze-e2e-failure
    test:
    - as: e2e
      cli: latest
      commands: make TEST_CLI=true test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    workflow: optional-operators-ci-aws
- always_run: false
  as: e2e-test-aws
  run_if_changed: .+\.go|go\.(\bmod\b|\bsum\b)|Makefile|Dockerfile|.dockerignore|.*\.ya{0,1}ml|build/.+|.sh
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OADP_BRANCH: oadp-dev
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      TEST_NAME: e2e-test-aws
    post:
    - ref: oadp-analyze-e2e-failure
    test:
    - as: e2e
      cli: latest
      commands: make test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    workflow: optional-operators-ci-aws
- as: e2e-test-aws-periodic
  cron: 0 4 * * *
  reporter_config:
    channel: '#oadp-cicd'
    job_states_to_report:
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}} :rainbow: Job *{{.Spec.Job}}*
      ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> :rainbow: {{else}}
      :alert-siren: Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View
      logs> :alert-siren: {{end}}'
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OADP_BRANCH: oadp-dev
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      TEST_NAME: e2e-test-aws-periodic
    post:
    - ref: oadp-analyze-e2e-failure
    test:
    - as: e2e
      cli: latest
      commands: make test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    workflow: optional-operators-ci-aws
- as: e2e-test-cli-aws-periodic
  cron: 0 2 * * *
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OADP_BRANCH: oadp-dev
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      TEST_NAME: e2e-test-cli-aws-periodic
    post:
    - ref: oadp-analyze-e2e-failure
    test:
    - as: e2e
      cli: latest
      commands: make TEST_CLI=true test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    workflow: optional-operators-ci-aws
- always_run: false
  as: tls-pqc-readiness
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      PQC_CHECK: "true"
      SCAN_NAMESPACE: openshift-adp
      SCANNER_CPU: "2"
    test:
    - ref: tls-13
    - ref: tls-scanner-run
    workflow: optional-operators-ci-aws
- as: tls-pqc-readiness-periodic
  cron: 0 6 * * 1
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      PQC_CHECK: "true"
      SCAN_NAMESPACE: openshift-adp
      SCANNER_CPU: "2"
    test:
    - ref: tls-13
    - ref: tls-scanner-run
    workflow: optional-operators-ci-aws
- always_run: false
  as: tls13-adherence
  optional: true
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      PQC_CHECK: "false"
      SCAN_NAMESPACE: openshift-adp
      SCANNER_CPU: "2"
      TLS_13_ENABLE_TLS_ADHERENCE: "true"
      TLS_13_TLS_ADHERENCE_POLICY: StrictAllComponents
    test:
    - ref: tls-13
    - ref: tls-scanner-run
    workflow: optional-operators-ci-aws
- as: tls13-adherence-periodic
  cron: 0 6 * * 1
  steps:
    cluster_profile: openshift-org-aws
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
      PQC_CHECK: "false"
      SCAN_NAMESPACE: openshift-adp
      SCANNER_CPU: "2"
      TLS_13_ENABLE_TLS_ADHERENCE: "true"
      TLS_13_TLS_ADHERENCE_POLICY: StrictAllComponents
    test:
    - ref: tls-13
    - ref: tls-scanner-run
    workflow: optional-operators-ci-aws
- always_run: false
  as: e2e-test-gcp-sts
  run_if_changed: .+\.go|go\.(\bmod\b|\bsum\b)|Makefile|Dockerfile|.dockerignore|.*\.ya{0,1}ml|build/.+|.sh
  steps:
    cluster_profile: openshift-org-gcp
    dependencies:
      OO_INDEX: ci-index
    env:
      OO_CHANNEL: dev
      OO_INSTALL_NAMESPACE: openshift-adp
      OO_PACKAGE: oadp-operator
      OO_TARGET_NAMESPACES: '!install'
    post:
    - chain: ipi-gcp-post-manual-oidc-workload-identity
    pre:
    - chain: ipi-gcp-pre-manual-oidc-workload-identity
    - ref: optional-operators-subscribe
    test:
    - as: e2e
      cli: latest
      commands: make test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
zz_generated_metadata:
  branch: oadp-dev
  org: openshift
  repo: oadp-operator
  variant: "4.22"
