label:
  restricted_labels:
    openshift/kube-rbac-proxy:
    - allowed_users:
      - tkashem
      - ibihim
      label: backport-risk-assessed
    - allowed_users:
      - xingxingxia
      - dpuniaredhat
plugins:
  openshift/kube-rbac-proxy:
    plugins:
    - approve
