approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  repos:
  - openshift-priv/operator-lifecycle-manager
  require_self_approval: true
lgtm:
- repos:
  - openshift-priv/operator-lifecycle-manager
  review_acts_as_lgtm: true
plugins:
  openshift-priv/operator-lifecycle-manager:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - wip
    - yuks
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift-priv/operator-lifecycle-manager
  trusted_apps:
  - openshift-merge-bot
