base_images:
  cli:
    name: "4.22"
    namespace: ocp
    tag: cli
  libvirt-installer:
    name: "4.22"
    namespace: ocp
    tag: libvirt-installer
  upi-installer:
    name: "4.22"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.25-openshift-4.22
canonical_go_repository: github.com/open-telemetry/opentelemetry-operator
images:
  items:
  - context_dir: .
    dockerfile_path: ./tests/e2e-openshift/Dockerfile
    to: obs-tests-runner
prowgen:
  enable_secrets_store_csi_driver: true
releases:
  latest:
    release:
      channel: stable
      version: "4.22"
  s390x-latest:
    release:
      architecture: s390x
      channel: stable
      version: "4.22"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: opentelemetry-stage-tests
  capabilities:
  - intranet
  cluster: build12
  cron: 0 0 30 2 *
  reporter_config:
    channel: '#distributed-tracing-qe'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}} :slack-green: Job *{{.Spec.Job}}*
      ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> {{else}} :failed:
      Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs>
      {{end}}'
  steps:
    cluster_profile: libvirt-s390x-vpn
    dependencies:
      OPENSHIFT_INSTALL_TARGET: release:s390x-latest
    env:
      AGENT_SKILL: otel
      ARCH: s390x
      BRANCH: "4.22"
      ETCD_DISK_SPEED: slow
      MULTISTAGE_PARAM_OVERRIDE_OTEL_INDEX_IMAGE: quay.io/redhat-user-workloads/ocp-art-tenant/art-fbc@sha256:bbef777a134275d4b8af90cc30d365e15575c66ba1a382b87e7d2ac479e68c87
      MULTISTAGE_PARAM_OVERRIDE_OTEL_TESTS_BRANCH: rhosdt-3.11
      NODE_TUNING: "true"
      OPERATORS: |
        [
            {"name": "tempo-product", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-tempo-operator", "target_namespaces": "", "operator_group": "openshift-tempo-operator"},
            {"name": "opentelemetry-product", "source": "otel-catalogsource", "channel": "stable", "install_namespace": "opentelemetry-operator-system", "target_namespaces": "", "operator_group": "opentelemetry-operator-system"},
            {"name": "amq-streams", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators", "target_namespaces": ""},
            {"name": "cluster-observability-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators", "target_namespaces": ""},
            {"name": "loki-operator", "source": "redhat-operators", "channel": "stable-6.5", "install_namespace": "openshift-operators-redhat","target_namespaces": "", "operator_group": "openshift-operators-redhat"},
            {"name": "cluster-logging", "source": "redhat-operators", "channel": "stable-6.5", "install_namespace": "openshift-logging","target_namespaces": "", "operator_group": "openshift-logging"}
        ]
      SKIP_TESTS: tests/e2e-instrumentation/* tests/e2e-multi-instrumentation/* tests/e2e-targetallocator/*
        tests/e2e-targetallocator-cr/* tests/e2e-prometheuscr/* tests/e2e-pdb/* tests/e2e-otel/*
        tests/e2e-metadata-filters/* tests/e2e-openshift-tls-profile/* tests/e2e/smoke-collector/smoke-collector-obi
        tests/e2e/smoke-collector/smoke-collector-obi-unprivileged tests/e2e-openshift/must-gather
        tests/e2e-openshift/export-to-cluster-logging-lokistack
      USE_EXTERNAL_DNS: "true"
    post:
    - ref: openshift-observability-qe-agent
    test:
    - ref: distributed-tracing-install-otel-konflux-catalogsource
    - ref: install-operators
    - ref: distributed-tracing-tests-opentelemetry-stage
    workflow: openshift-e2e-libvirt-vpn
zz_generated_metadata:
  branch: main
  org: openshift
  repo: open-telemetry-opentelemetry-operator
  variant: opentelemetry-product-ocp-4.22-ibm-z-stage
