plugins:
  openshift-priv/stolostron-postgres_exporter:
    plugins:
    - approve
    - assign
    - golint
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - retitle
    - shrug
    - trigger
    - verify-owners
    - wip
