approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  ignore_review_state: true
  repos:
  - openshift-kni/baremetal-deploy
  require_self_approval: true
triggers:
- repos:
  - openshift-kni/baremetal-deploy
  trusted_apps:
  - red-hat-konflux
