plugins:
  openshift-priv/quay-container-security-operator:
    plugins:
    - cat
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lifecycle
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - verify-owners
    - wip
    - yuks
triggers:
- repos:
  - openshift-priv/quay-container-security-operator
  trusted_apps:
  - dependabot
  - openshift-merge-bot
