base_images:
  baremetal-qe-base:
    name: baremetal-qe-base
    namespace: ci
    tag: latest
  openshift-virtualization-tests:
    name: openshift-virtualization-tests
    namespace: ci
    tag: cnv-4.20
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: deploy-cluster
  capabilities:
  - intranet
  cron: 0 23 31 2 *
  reporter_config:
    channel: '#team-qe-lp-triage'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}} :slack-green: Job *{{.Spec.Job}}*
      ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> {{else}} :failed:
      Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs>
      {{end}}'
  steps:
    allow_best_effort_post_steps: true
    cluster_profile: metal-redhat-gs
    env:
      OCP__ABI__BM__BASE_DOM: sys.eng.rdu2.dc.redhat.com
      OCP__ABI__BM__CLS_NAME: integrity
      OCP__ABI__TEAM_NAME: lp-interop
      OCP__ABI__TUN_SVC__CP_URL: https://chisel.lp-chaos--svc--web-app.chaos.lp.devcluster.openshift.com/cp
      OCP__ABI__TUN_SVC__DP_BASE_URL: https://chisel.lp-chaos--svc--web-app.chaos.lp.devcluster.openshift.com/dp
      OCP__ABI__TUN_SVC__DP_PORT: "20000"
    workflow: abi-workflows-bm--bmc--cluster-health
  timeout: 4h0m0s
- as: net--localnet
  capabilities:
  - intranet
  cron: 0 6 * * 1
  reporter_config:
    channel: '#team-qe-lp-triage'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}} :slack-green: Job *{{.Spec.Job}}*
      ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> {{else}} :failed:
      Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs>
      {{end}}'
  steps:
    allow_best_effort_post_steps: true
    cluster_profile: metal-redhat-gs
    env:
      OCP__ABI__BM__BASE_DOM: sys.eng.rdu2.dc.redhat.com
      OCP__ABI__BM__CLS_NAME: integrity
      OCP__ABI__TEAM_NAME: lp-interop
      OCP__ABI__TUN_SVC__CP_URL: https://chisel.lp-chaos--svc--web-app.chaos.lp.devcluster.openshift.com/cp
      OCP__ABI__TUN_SVC__DP_BASE_URL: https://chisel.lp-chaos--svc--web-app.chaos.lp.devcluster.openshift.com/dp
      OCP__ABI__TUN_SVC__DP_PORT: "20000"
      OCP_VERSION: "4.20"
    test:
    - ref: gs-baremetal-localnet-test
    workflow: abi-workflows-bm--bmc--cluster-health
  timeout: 8h0m0s
zz_generated_metadata:
  branch: master
  org: RedHatQE
  repo: interop-testing
  variant: gs-baremetal--ocp4.20--lp-hw
