#We put only the customized fields in git
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: docker-registry
              operator: In
              values:
              - default
          topologyKey: "kubernetes.io/hostname"
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  operatorLogLevel: Normal
  replicas: 5
  storage:
    managementState: Managed
    s3:
      bucket: hosted-mgmt-image-registry
      encrypt: true
      region: us-east-1
      regionEndpoint: https://2209d6dda25891dee55b086a469130de.r2.cloudflarestorage.com
      trustedCA:
        name: ""
      virtualHostedStyle: false
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
