#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

echo "===== Precheck: Ensure required tools are present ====="
for cmd in skopeo git az bicep yq jq; do
  if ! command -v "$cmd" &> /dev/null; then
    echo "ERROR: Required tool '$cmd' is not installed or not in PATH."
    exit 1
  fi
done
echo "All required tools are present: skopeo, git, az, bicep."

echo "===== Configure Azure Authentication ====="
export AZURE_CLIENT_ID
AZURE_CLIENT_ID=$(cat /var/run/hcp-integration-credentials/client-id)
export AZURE_CLIENT_SECRET
AZURE_CLIENT_SECRET=$(cat /var/run/hcp-integration-credentials/client-secret)
export AZURE_TENANT_ID
AZURE_TENANT_ID=$(cat /var/run/hcp-integration-credentials/tenant)

# Configure git
git config user.name "openshift-ci-robot"
git config user.email "openshift-ci-robot@users.noreply.github.com"

echo "===== Building image-updater ====="
cd tooling/image-updater
make build

echo "===== Running image-updater for all components ====="
./image-updater update --config config.yaml | tee /tmp/image-updater-output.txt

# Check if there are any changes
if [[ $(git status --porcelain) == "" ]]; then
  echo "No image updates needed for any components"
  exit 0
fi

cd ../..

git add .
git commit -m "chore: execute image-updater for all components"

echo "===== Rendering ACM helm-charts ====="
make -C acm helm-charts

if [[ $(git status --porcelain) != "" ]]; then
  make yamlfmt 2> /dev/null \
    && UPDATE=true go test ./tooling/helmtest/... 2> /dev/null
  git add .
  git commit -m "chore: render ACM helm-charts"
fi

echo "===== Materializing configuration ====="
make -C config materialize
git add .
git commit -m "chore: render digests using materialize"

echo "===== Changes detected ====="
git status --short

echo "===== Creating PR ====="
# Use the image-updater output directly for PR message
UPDATE_SUMMARY=$(cat /tmp/image-updater-output.txt)

/usr/bin/prcreator \
  -github-token-path=/etc/github/oauth \
  -organization=Azure \
  -repo=ARO-HCP \
  -branch=main \
  -pr-title="Automated - Update component image digests" \
  -pr-message="This automated PR updates ARO-HCP container image digests to the latest versions from registries.

${UPDATE_SUMMARY}

---
**Schedule:** Monday through Friday at 2 AM UTC  
**Generated by:** [periodic-ci-Azure-ARO-HCP-main-image-updater-tooling](https://prow.ci.openshift.org/?job=periodic-ci-Azure-ARO-HCP-main-image-updater-tooling)
"

echo "===== Sending Slack notification ====="
WEBHOOK_URL=$(cat /var/run/slack-webhook/webhook)
curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"🔄 Image digest update PR created. Please review: https://github.com/Azure/ARO-HCP/pulls?q=is%3Apr+is%3Aopen+author%3Aopenshift-ci-robot\"}" "${WEBHOOK_URL}"