#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

log() { echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $*"; }
info()  { if [[ ${DEBUG-0} -ge 0 ]]; then log "[info] $*"; fi }
debug() { if [[ ${DEBUG-0} -ge 1 ]]; then log "[debug] $*"; fi }
error() { log "[error] $*"; exit 1; }

debug "precheck: ensure required tools are present"
for cmd in skopeo git az bicep yq jq; do
  command -v "$cmd" &> /dev/null || error "required tool '$cmd' is not installed or not in PATH."
done; debug "precheck: all required tools are present"

debug "azure: configure Azure Authentication"
export AZURE_CLIENT_ID; AZURE_CLIENT_ID=$(cat /var/run/hcp-integration-credentials/client-id)
export AZURE_CLIENT_SECRET; AZURE_CLIENT_SECRET=$(cat /var/run/hcp-integration-credentials/client-secret)
export AZURE_TENANT_ID; AZURE_TENANT_ID=$(cat /var/run/hcp-integration-credentials/tenant)

debug "git: configure git user and email"
git config user.name "openshift-ci-robot"
git config user.email "openshift-ci-robot@users.noreply.github.com"

debug "image: change to tooling/image-updater directory"
cd tooling/image-updater

debug "image: build image-updater binary"
make build

export IMAGE_UPDATER_OUTPUT=/tmp/image-updater-output.txt

info "image: fetching the latest image digests for all components"
if [[ ${DEBUG-0} -ge 1 ]]; then
  ./image-updater update --verbosity 3 --config config.yaml | tee "${IMAGE_UPDATER_OUTPUT}"
else
  ./image-updater update --config config.yaml > "${IMAGE_UPDATER_OUTPUT}"
fi

debug "image: return to root directory"
cd ../..

# Check if there are any changes
if [[ $(git status --porcelain) == "" ]]; then
  info "image: no new digests found for any component images"
  exit 0
fi

info "git: commiting updated image digests"
git commit --all --quiet --message "chore: execute image-updater for all components"

info "acm: rendering ACM helm-charts"
if [[ ${DEBUG-0} -ge 1 ]]; then
  make -C acm helm-charts
else
  make -C acm helm-charts > /dev/null 2>&1
fi

if [[ $(git status --porcelain) != "" ]]; then
  debug "acm: running yaml formating and updating helm fixtures"
  if [[ ${DEBUG-0} -ge 1 ]]; then
    make yamlfmt && make update-helm-fixtures
  else
    make yamlfmt > /dev/null 2>&1 && make update-helm-fixtures > /dev/null 2>&1
  fi

  info "git: commiting rendered helm charts"
  git commit --all --quiet --message "chore: render ACM helm-charts"
else
  info "acm: no changes to helm charts"
fi

info "image: materializing configuration"
if [[ ${DEBUG-0} -ge 1 ]]; then
  make -C config materialize
else
  make -C config materialize > /dev/null 2>&1
fi

info "git: creating Pull Request"

debug "git: changes to be merged into main"
if [[ ${DEBUG-0} -ge 1 ]]; then
  git diff main
fi

/usr/bin/prcreator \
  -github-token-path=/etc/github/oauth \
  -organization=Azure \
  -repo=ARO-HCP \
  -branch=main \
  -git-message="chore: render digests using materialize" \
  -pr-title="Automated - Update component image digests" \
  -pr-message="This automated PR updates ARO-HCP container image digests to the latest versions from registries.

$(cat "${IMAGE_UPDATER_OUTPUT}")

---
**Schedule:** Monday through Friday at 2 AM UTC  
**Generated by:** [periodic-ci-Azure-ARO-HCP-main-image-updater-tooling](https://prow.ci.openshift.org/?job=periodic-ci-Azure-ARO-HCP-main-image-updater-tooling)
**Generated at:** $(date +%Y-%m-%dT%H:%M:%S%z)
"

info "slack: sending notification"
WEBHOOK_URL=$(cat /var/run/slack-webhook/webhook)
curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"🔄 Image digest update PR created. Please review: https://github.com/Azure/ARO-HCP/pulls?q=is%3Apr+is%3Aopen+author%3Aopenshift-ci-robot\"}" "${WEBHOOK_URL}"