#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

log() { echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $*"; }
info()  { if [[ ${DEBUG-0} -ge 0 ]]; then log "[info] $*"; fi }
debug() { if [[ ${DEBUG-0} -ge 1 ]]; then log "[debug] $*"; fi }
error() { log "[error] $*"; exit 1; }

notify() {
  WEBHOOK_URL=$(cat /var/run/slack-webhook/webhook)
  curl -sq -X POST -H 'Content-type: application/json' --data "{\"text\":\"$*\"}" "${WEBHOOK_URL}"
}

debug "precheck: ensure required tools are present"
for cmd in skopeo git az bicep yq jq; do
  command -v "$cmd" &> /dev/null || error "required tool '$cmd' is not installed or not in PATH."
done; debug "precheck: all required tools are present"

debug "azure: configure Azure Authentication"
export AZURE_CLIENT_ID; AZURE_CLIENT_ID=$(cat /var/run/hcp-integration-credentials/client-id)
export AZURE_CLIENT_SECRET; AZURE_CLIENT_SECRET=$(cat /var/run/hcp-integration-credentials/client-secret)
export AZURE_TENANT_ID; AZURE_TENANT_ID=$(cat /var/run/hcp-integration-credentials/tenant)

debug "cfg: set environment variables"
export PROW_JOB_URL="https://prow.ci.openshift.org/?job=periodic-ci-Azure-ARO-HCP-main-image-updater-image-updater-tooling"
export IMAGE_UPDATER_OUTPUT="/tmp/image-updater-output.txt"
export GIT_PR_TITLE="Automated - Update component image digests"
export GIT_PR_USER="openshift-ci-robot"
export GIT_PR_EMAIL="openshift-ci-robot@users.noreply.github.com"

debug "git: configure git user and email"
git config user.name "${GIT_PR_USER}"
git config user.email "${GIT_PR_EMAIL}"

debug "image: change to tooling/image-updater directory"
cd tooling/image-updater

debug "image: build image-updater binary"
make build

info "image: fetching the latest image digests for all components"
if [[ ${DEBUG-0} -ge 1 ]]; then
  ./image-updater update --verbosity 1 --config config.yaml | tee "${IMAGE_UPDATER_OUTPUT}"
else
  ./image-updater update --config config.yaml > "${IMAGE_UPDATER_OUTPUT}"
fi

debug "image: return to root directory"
cd ../..

# Check if there are any changes
if [[ $(git status --porcelain) == "" ]]; then
  info "image: no new digests found for any component images"
  notify "⚠️ Image digest updater job completed but no new digests found for any component images. Please check [prow](${PROW_JOB_URL})."
  exit 0
fi

info "git: commiting updated image digests"
git commit --all --quiet --message "chore: execute image-updater for all components"

info "acm: rendering ACM helm-charts"
if [[ ${DEBUG-0} -ge 1 ]]; then
  make -C acm helm-charts
else
  make -C acm helm-charts > /dev/null 2>&1
fi

if [[ $(git status --porcelain) != "" ]]; then
  debug "acm: running yaml formating and updating helm fixtures"
  if [[ ${DEBUG-0} -ge 1 ]]; then
    make yamlfmt && make update-helm-fixtures
  else
    make yamlfmt > /dev/null 2>&1 && make update-helm-fixtures > /dev/null 2>&1
  fi

  info "git: commiting rendered helm charts"
  git commit --all --quiet --message "chore: render ACM helm-charts"
else
  info "acm: no changes to helm charts"
fi

info "image: materializing configuration"
if [[ ${DEBUG-0} -ge 1 ]]; then
  make -C config materialize
else
  make -C config materialize > /dev/null 2>&1
fi

info "git: creating Pull Request"

debug "git: changes to be merged into main"
if [[ ${DEBUG-0} -ge 1 ]]; then
  git diff main
fi

/usr/bin/prcreator \
  -github-token-path=/etc/github/oauth \
  -organization=Azure \
  -repo=ARO-HCP \
  -branch=main \
  -git-message="chore: render digests using materialize" \
  -pr-title="${GIT_PR_TITLE}" \
  -pr-message="This automated PR updates ARO-HCP container image digests to the latest versions from registries.

$(cat "${IMAGE_UPDATER_OUTPUT}")

---
**Schedule:** Monday through Friday at 2 AM UTC  
**Generated by:** [periodic-ci-Azure-ARO-HCP-main-image-updater-tooling](${PROW_JOB_URL})
**Generated at:** $(date +%Y-%m-%dT%H:%M:%S%z)
"

info "github: checking for existing PR"
PR_CHECK_MAX_ATTEMPTS=${PR_CHECK_MAX_ATTEMPTS:-5}
for ((i=1; i<=PR_CHECK_MAX_ATTEMPTS; i++)); do
  debug "github: Waiting for the PR to be created..."
  PR_URL=$(curl -s "https://api.github.com/repos/Azure/ARO-HCP/pulls?per_page=100" | jq -r ".[] | select(.user.login == \"${GIT_PR_USER}\" and .title == \"${GIT_PR_TITLE}\") | .html_url" | head -1)

  if [ -n "$PR_URL" ]; then
    info "github: PR found at $PR_URL"
    break
  fi

  if [ $i -lt $PR_CHECK_MAX_ATTEMPTS ]; then
    debug "github: No PR found, waiting 30 seconds... ($i of $PR_CHECK_MAX_ATTEMPTS retries)"
    sleep 30
  fi
done

info "slack: sending notification for PR creation"
if [ -z "$PR_URL" ]; then
  notify "❌ Image digest updater job failed, no PR found after $PR_CHECK_MAX_ATTEMPTS attempts. Please check [prow](${PROW_JOB_URL})."
  error "github: No PR found after $PR_CHECK_MAX_ATTEMPTS attempts"
fi
notify "✅ Image digest update PR created at $PR_URL. Please review and approve the changes."
exit 0