presubmits:
  openshift/managed-cluster-config:
  - agent: kubernetes
    always_run: true
    branches:
    - ^master$
    - ^master-
    cluster: build09
    context: ci/prow/checklinks-pr
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      ci.openshift.io/generator: prowgen
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-managed-cluster-config-master-checklinks-pr
    optional: true
    rerun_command: /test checklinks-pr
    spec:
      containers:
      - args:
        - --gcs-upload-secret=/secrets/gcs/service-account.json
        - --image-import-pull-secret=/etc/pull-secret/.dockerconfigjson
        - --report-credentials-file=/etc/report/credentials
        - --target=checklinks-pr
        command:
        - ci-operator
        env:
        - name: HTTP_SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay-proxy.ci.openshift.org/openshift/ci:ci_ci-operator_latest
        imagePullPolicy: Always
        name: ""
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /secrets/gcs
          name: gcs-credentials
          readOnly: true
        - mountPath: /secrets/manifest-tool
          name: manifest-tool-local-pusher
          readOnly: true
        - mountPath: /etc/pull-secret
          name: pull-secret
          readOnly: true
        - mountPath: /etc/report
          name: result-aggregator
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: manifest-tool-local-pusher
        secret:
          secretName: manifest-tool-local-pusher
      - name: pull-secret
        secret:
          secretName: registry-pull-credentials
      - name: result-aggregator
        secret:
          secretName: result-aggregator
    trigger: (?m)^/test( | .* )checklinks-pr,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - ^master$
    - ^master-
    cluster: build12
    context: ci/prow/hive-e2e-sss-dryrun
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      capability/intranet: intranet
      ci-operator.openshift.io/cloud: aws
      ci-operator.openshift.io/cloud-cluster-profile: rosa-e2e-01
      ci.openshift.io/generator: prowgen
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-managed-cluster-config-master-hive-e2e-sss-dryrun
    rerun_command: /test hive-e2e-sss-dryrun
    spec:
      containers:
      - args:
        - --enable-secrets-store-csi-driver=true
        - --gcs-upload-secret=/secrets/gcs/service-account.json
        - --gsm-config=/etc/gsm-config/gsm-config.yaml
        - --gsm-credentials-file=/etc/gsm-credentials/key.json
        - --gsm-project-config=/etc/gsm-config/gsm-project-config.yaml
        - --image-import-pull-secret=/etc/pull-secret/.dockerconfigjson
        - --lease-server-credentials-file=/etc/boskos/credentials
        - --report-credentials-file=/etc/report/credentials
        - --target=hive-e2e-sss-dryrun
        command:
        - ci-operator
        env:
        - name: HTTP_SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay-proxy.ci.openshift.org/openshift/ci:ci_ci-operator_latest
        imagePullPolicy: Always
        name: ""
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /etc/boskos
          name: boskos
          readOnly: true
        - mountPath: /secrets/gcs
          name: gcs-credentials
          readOnly: true
        - mountPath: /etc/gsm-config
          name: gsm-config
          readOnly: true
        - mountPath: /etc/gsm-credentials
          name: gsm-sa-key
          readOnly: true
        - mountPath: /secrets/manifest-tool
          name: manifest-tool-local-pusher
          readOnly: true
        - mountPath: /etc/pull-secret
          name: pull-secret
          readOnly: true
        - mountPath: /etc/report
          name: result-aggregator
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: boskos
        secret:
          items:
          - key: credentials
            path: credentials
          secretName: boskos-credentials
      - configMap:
          name: gsm-config
        name: gsm-config
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: ci-operator-sa-key-spc
        name: gsm-sa-key
      - name: manifest-tool-local-pusher
        secret:
          secretName: manifest-tool-local-pusher
      - name: pull-secret
        secret:
          secretName: registry-pull-credentials
      - name: result-aggregator
        secret:
          secretName: result-aggregator
    trigger: (?m)^/test( | .* )hive-e2e-sss-dryrun,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - ^master$
    - ^master-
    cluster: build09
    context: ci/prow/pr-check
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      ci.openshift.io/generator: prowgen
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-managed-cluster-config-master-pr-check
    rerun_command: /test pr-check
    spec:
      containers:
      - args:
        - --gcs-upload-secret=/secrets/gcs/service-account.json
        - --image-import-pull-secret=/etc/pull-secret/.dockerconfigjson
        - --report-credentials-file=/etc/report/credentials
        - --target=pr-check
        command:
        - ci-operator
        env:
        - name: HTTP_SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay-proxy.ci.openshift.org/openshift/ci:ci_ci-operator_latest
        imagePullPolicy: Always
        name: ""
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /secrets/gcs
          name: gcs-credentials
          readOnly: true
        - mountPath: /secrets/manifest-tool
          name: manifest-tool-local-pusher
          readOnly: true
        - mountPath: /etc/pull-secret
          name: pull-secret
          readOnly: true
        - mountPath: /etc/report
          name: result-aggregator
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: manifest-tool-local-pusher
        secret:
          secretName: manifest-tool-local-pusher
      - name: pull-secret
        secret:
          secretName: registry-pull-credentials
      - name: result-aggregator
        secret:
          secretName: result-aggregator
    trigger: (?m)^/test( | .* )pr-check,?($|\s.*)
