build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: console-plugin-test-cypress-v18
images:
  items:
  - dockerfile_path: Dockerfile
    to: node-remediation-console
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.22"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: release-0.4
  org: medik8s
  repo: node-remediation-console
