ref:
  as: openshift-qe-day2-config
  from_image:
    namespace: ci
    name: ocp-qe-perfscale-ci
    tag: latest
  cli: latest
  commands: openshift-qe-day2-config-commands.sh
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
  - name: DAY2_CONFIG
    default: ""
    documentation: |-
      The feature to configure for day2 configuration. e.g. gateway-api.
  documentation: |-
    Day2 configuration for a cluster.

