#!/bin/bash
set -e
set -o pipefail

# Fix user IDs in a container
~/fix_uid.sh

SSH_KEY_PATH=/var/run/ssh-key/ssh-key
SSH_KEY=~/key
BASTION_IP_ADDR="$(cat /var/run/bastion-ip-addr/address)"
JENKINS_USER_NAME="$(cat /var/run/jenkins-credentials/jenkins-username)"
JENKINS_USER_TOKEN="$(cat /var/run/jenkins-credentials/jenkins-token)"

# Check connectivity
ping $BASTION_IP_ADDR -c 10 || true
echo "exit" | curl "telnet://$BASTION_IP_ADDR:22" && echo "SSH port is opened"|| echo "status = $?"

cp $SSH_KEY_PATH $SSH_KEY
chmod 600 $SSH_KEY

git clone https://github.com/openshift-kni/eco-ci-cd --depth=1 ${SHARED_DIR}/eco-ci-cd
cd ${SHARED_DIR}/eco-ci-cd/
ansible-galaxy collection install redhatci.ocp --ignore-certs


PARAMS=$(cat <<END_CAT
HOST=$LOCK_LBL_HOST&\
OCP_MAJOR_VERSION=$OCP_MAJOR_VERSION&\
OCP_MINOR_VERSION=$OCP_MINOR_VERSION&\
OPENSHIFT_RELEASE_IMAGE=$OPENSHIFT_RELEASE_IMAGE&\
PROVISION=$PROVISION&\
DEPLOY=$DEPLOY&\
DEPLOY_BREAKPOINTS=$DEPLOY_BREAKPOINTS&\
MANAGEMENT_INTERFACE_TYPE=$MANAGEMENT_INTERFACE_TYPE&\
PROVISIONING_NETWORK_STATE=$PROVISIONING_NETWORK_STATE&\
NETWORK_TYPE=$NETWORK_TYPE&\
ENABLE_IPSEC=$ENABLE_IPSEC&\
BAREMETAL_NET_IPV4=$BAREMETAL_NET_IPV4&\
BAREMETAL_NET_IPV6=$BAREMETAL_NET_IPV6&\
PROVISIONING_NET_IPV6=$PROVISIONING_NET_IPV6&\
DHCP_LEASE_TIME=$DHCP_LEASE_TIME&\
USE_BOND_INTERFACE=$USE_BOND_INTERFACE&\
BOND_CONFIG=$BOND_CONFIG&\
USE_STATIC_IP_CONFIG=$USE_STATIC_IP_CONFIG&\
DISCONNECTED_INSTALL=$DISCONNECTED_INSTALL&\
USE_NEXUS_CACHE=$USE_NEXUS_CACHE&\
PROXY_INSTALL=$PROXY_INSTALL&\
PREDEPLOY_VALIDATE=$PREDEPLOY_VALIDATE&\
FIPS_MODE=$FIPS_MODE&\
BM_IRONIC_BOOT_MODE=$BM_IRONIC_BOOT_MODE&\
VM_UEFI_FIRMWARE=$VM_UEFI_FIRMWARE&\
CLUSTER_NAME=$CLUSTER_NAME&\
CLUSTER_COUNT=$CLUSTER_COUNT&\
BASE_DOMAIN=$BASE_DOMAIN&\
PRESERVE_BOOTSTRAP=$PRESERVE_BOOTSTRAP&\
NESTED_BOOTSTRAP_VM=$NESTED_BOOTSTRAP_VM&\
PROVISION_MASTER_COUNT=$PROVISION_MASTER_COUNT&\
DEPLOY_MASTER_COUNT=$DEPLOY_MASTER_COUNT&\
MASTER_DISK_SIZE=$MASTER_DISK_SIZE&\
MASTER_VCPUS=$MASTER_VCPUS&\
MASTER_EXTRA_DISK_COUNT=$MASTER_EXTRA_DISK_COUNT&\
MASTER_EXTRA_DISK_SIZE=$MASTER_EXTRA_DISK_SIZE&\
MASTER_MEMORY=$MASTER_MEMORY&\
MASTER_ROOT_DISK_HINT_NAME=$MASTER_ROOT_DISK_HINT_NAME&\
MASTER_ROOT_DISK_HINT_VALUE=$MASTER_ROOT_DISK_HINT_VALUE&\
PROVISION_WORKER_COUNT=$PROVISION_WORKER_COUNT&\
DEPLOY_WORKER_COUNT=$DEPLOY_WORKER_COUNT&\
WORKER_DISK_SIZE=$WORKER_DISK_SIZE&\
WORKER_VCPUS=$WORKER_VCPUS&\
WORKER_EXTRA_DISK_COUNT=$WORKER_EXTRA_DISK_COUNT&\
WORKER_EXTRA_DISK_SIZE=$WORKER_EXTRA_DISK_SIZE&\
WORKER_MEMORY=$WORKER_MEMORY&\
WORKER_ROOT_DISK_HINT_NAME=$WORKER_ROOT_DISK_HINT_NAME&\
WORKER_ROOT_DISK_HINT_VALUE=$WORKER_ROOT_DISK_HINT_VALUE&\
OCP_EDGE_REPO=$OCP_EDGE_REPO&\
OCP_EDGE_BRANCH=$OCP_EDGE_BRANCH&\
PROFILE_NAME=$PROFILE_NAME&\
PROFILE_OVERRIDE=$PROFILE_OVERRIDE&\
COLLECT_LOGS=$COLLECT_LOGS&\
CREATE_QEMU_SNAPSHOT=$CREATE_QEMU_SNAPSHOT&\
JOB_RETRIES=$JOB_RETRIES&\
PRECLEAN_LOCAL_REGISTRY=$PRECLEAN_LOCAL_REGISTRY&\
END_CAT
)

PARAMS=$(echo "$PARAMS" | tr -d '\n')
ansible-playbook playbooks/launch-jenkins-job.yaml -i inventory \
 -e username=$JENKINS_USER_NAME \
 -e token=$JENKINS_USER_TOKEN \
 -e job_params="$PARAMS" -e job_url="https://auto-jenkins-csb-kniqe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-baremetal-ipi-deployment/" -vvv
