approve:
- repos:
  - openshift/test-harness-operator
  require_self_approval: false
lgtm:
- repos:
  - openshift/test-harness-operator
  review_acts_as_lgtm: true
plugins:
  openshift/test-harness-operator:
    plugins:
    - approve
triggers:
- repos:
  - openshift/test-harness-operator
  trusted_apps:
  - openshift-merge-bot
