approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  repos:
  - openshift-kni/commatrix
  require_self_approval: false
lgtm:
- repos:
  - openshift-kni/commatrix
  review_acts_as_lgtm: true
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift-kni/commatrix
  trusted_apps:
  - red-hat-konflux
  - openshift-merge-bot
