apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  annotations:
    version_lower: 4.23.0-0
    version_stream: 4.23.0-0.nightly
    version_upper: 4.24.0-0
  name: ocp-release-nightly-sha256-0ba2ab89025cf344ff939c8c46c3cdbe863da49d1fd691ec283a0e1668c66ad2-for-4.23.0-0-to-4.24.0-0
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release-nightly@sha256:0ba2ab89025cf344ff939c8c46c3cdbe863da49d1fd691ec283a0e1668c66ad2
status: {}
