plugins:
  openshift-priv/metal3-smart-exporter:
    plugins:
    - approve
    - golint
    - goose
    - jira
    - owners-label
    - pony
    - sigmention
triggers:
- repos:
  - openshift-priv/metal3-smart-exporter
  trusted_apps:
  - openshift-merge-bot
