{
 "title": "GitHub Cache",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "login",
    "label": "login",
    "query": "label_values(github:identity_names, login)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(github_request_duration_count, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(github_request_duration_count, status)"
   },
   {
    "name": "user_agent",
    "label": "user_agent",
    "query": "label_values(github_request_duration_count, user_agent)"
   },
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Cache Requests (per hour)",
   "type": "graph",
   "description": "Count of cache requests of each cache mode over the last hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login)) by (mode)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login))",
     "legendFormat": "(No Cost)"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "graph",
   "description": "Percentage of cacheable requests that are fulfilled for free.\nNo cost modes are \"COALESCED\" and \"REVALIDATED\".\nCacheable modes include the no cost modes, \"CHANGED\" and \"MISS\".",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\", token_hash=~\"openshift-ci - .*\"}[1h]))  / sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\", token_hash=~\"openshift-ci - .*\"}[1h]))",
     "legendFormat": "App"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login)) \n/ sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login))",
     "legendFormat": "Token"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_used) without (instance,pod)",
     "legendFormat": "GB Used"
    },
    {
     "expr": "avg(ghcache_disk_free) without (instance,pod)",
     "legendFormat": "GB Free"
    }
   ]
  },
  {
   "title": "Disk Inode Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_inode_used) without (instance,pod)",
     "legendFormat": "Inodes used"
    },
    {
     "expr": "avg(ghcache_disk_inode_free) without (instance,pod)",
     "legendFormat": "Inodes Free"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last hour",
   "type": "singlestat",
   "description": "The number of no cost requests in the last hour.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login))"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last 7 days",
   "type": "singlestat",
   "description": "The number of no cost requests in the last 7 days.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[7d]) * on(token_hash) group_left(login) max(github_user_info{login=~\"openshift-.*\"}) by (token_hash, login))"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "graph",
   "description": "GitHub token usage by login and API version.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(github_token_usage{token_hash=~\"${login}\"}) by (token_hash, api_version)",
     "legendFormat": "{{token_hash}} : {{api_version}}"
    },
    {
     "expr": "sum(github_token_usage * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (api_version, login)",
     "legendFormat": "{{login}} : {{api_version}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview for identity ${login} by status with ${range}",
   "type": "graph",
   "description": "GitHub request rates by status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{token_hash=~\"${login}\"}[${range}])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(github_request_duration_count[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview for identity ${login} by path for status ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by path.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{status=\"${status}\",token_hash=~\"${login}\"}[${range}])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(rate(github_request_duration_count{status=\"${status}\"}[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Rates: Identity ${login}, path ${path}, and status ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by login, path and status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{path=~\"${path}\", status=\"${status}\", token_hash=~\"${login}\"}[${range}])) by (login, path, status)",
     "legendFormat": "{{status}}: {{path}}"
    },
    {
     "expr": "sum(rate(github_request_duration_count{path=~\"${path}\", status=\"${status}\"}[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (login, path, status)",
     "legendFormat": "{{status}}: {{path}}"
    }
   ]
  },
  {
   "title": "Latency Distribution Overview with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Latency Distribution for path ${path} and ${status} with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=~\"${status}\"}[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\", token_hash=~\"${login}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\", token_hash=~\"${login}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\", token_hash=~\"${login}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Token Consumption for identity ${login} by User Agent",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h])) by (user_agent) != 0",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",token_hash=~\"${login}\"}[1h])) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Token Consumption for identity ${login} by Path",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h])) by (path) != 0",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",token_hash=~\"${login}\"}[1h])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Token Consumption for identity ${login} at Path ${path} by User Agent",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",path=\"${path}\"}[1h])) by (user_agent) != 0",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",path=~\"${path}\",token_hash=~\"${login}\"}[1h])) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",path=~\"${path}\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Token Consumption for identity ${login} and User Agent ${user_agent} by Path",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",user_agent=\"${user_agent}\"}[1h])) by (path) != 0",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",user_agent=~\"${user_agent}\",token_hash=~\"${login}\"}[1h])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",user_agent=~\"${user_agent}\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}