approve:
- repos:
  - openshift/console-plugin-template
  require_self_approval: false
label:
  restricted_labels:
    openshift/console-plugin-template:
    - allowed_users:
      - jhadvig
      - logonoff
      - rhamilto
      - spadgett
      - therealjon
      - vojtechszocs
      label: backport-risk-assessed
lgtm:
- repos:
  - openshift/console-plugin-template
  review_acts_as_lgtm: true
plugins:
  openshift/console-plugin-template:
    plugins:
    - approve
