build_root:
  project_image:
    dockerfile_literal: |
      FROM registry.access.redhat.com/ubi9/nodejs-22:latest
      USER 1001
prowgen:
  expose: true
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: openapi-validate
  commands: HOME=/tmp npm install && npm test
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-trusted-actions-api
