build_root:
  image_stream_tag:
    name: eco-ci-cd
    namespace: telcov10n-ci
    tag: eco-ci-cd
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: compute-nto-functional-tests
  capabilities:
  - intranet
  cron: 0 1 * * 5
  steps:
    env:
      CLUSTER_NAME: hlxcl15
      CONTAINER_RUNTIME: runc
      ECO_GOTEST_BMC_ACCESS: "true"
      ECO_GOTESTS_ENV_VARS: -e ECO_CNF_CORE_COMPUTE_TEST_CONTAINER=quay.io/ocp-edge-qe/eco-gotests-compute-client:v4.18
        -e ECO_CNF_CORE_COMPUTE_NTO_TEST_CONTAINER=quay.io/ocp-edge-qe/eco-gotests-nto:v4.18
      FEATURES: compute
      HUGEPAGES_DEFAULT_SIZE: 1G
      HUGEPAGES_PAGES: '[{"count": 1, "size": "1G"}, {"count": 128, "size": "2M"}]'
      IGNORE_CGROUPS_VERSION: "true"
      LABELS: nto
      RT_KERNEL: "false"
      VERSION: "4.18"
    test:
    - ref: telcov10n-functional-compute-nto-eco-gotests
    workflow: telcov10n-functional-compute-nto-ocp-setup
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: eco-ci-cd
  variant: compute-nto-hlxcl15
