build_root:
  image_stream_tag:
    name: eco-ci-cd
    namespace: telcov10n-ci
    tag: eco-ci-cd
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cnf-ran-ztp-tests
  capabilities:
  - intranet
  cron: 0 0 31 2 *
  steps:
    env:
      CLUSTER_NAME: kni-qe-106
      DISABLE_INSIGHTS: "true"
      VERSION: "4.20"
    pre:
    - ref: telcov10n-functional-cnf-ran-hub-deploy
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: eco-ci-cd
  variant: cnf-ran-sno-day2-worker-4.20
