build_root:
  image_stream_tag:
    name: eco-ci-cd
    namespace: telcov10n-ci
    tag: eco-ci-cd
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.17"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cnf-network-functional-tests
  capabilities:
  - intranet
  cron: 0 23 * * 4
  restrict_network_access: true
  steps:
    env:
      VERSION: "4.17"
    workflow: telcov10n-functional-cnf-network-ocp-setup
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: eco-ci-cd
  variant: cnf-network-4.17
