build_root:
  from_repository: true
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.21"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-upgrade
  cron: 0 6 * * 1
  steps:
    allow_best_effort_post_steps: true
    cluster_profile: openshift-org-aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:initial
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:latest
    env:
      TEST_SUITE: ""
      TEST_TYPE: upgrade
      TEST_UPGRADE_OPTIONS: ""
    post:
    - ref: descheduler-post-upgrade-verify-and-test
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre-stableinitial
    test:
    - ref: descheduler-olm-install
    - ref: openshift-e2e-test
zz_generated_metadata:
  branch: release-4.22
  org: openshift
  repo: cluster-kube-descheduler-operator
  variant: nightly-4.22-upgrade-from-nightly-4.21
