base_images:
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: workflow-classic-nightly-4-19
  cron: 0 9 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "4.19"
      REGION: us-west-2
    workflow: rosa-gap-analysis-classic
- as: workflow-hcp-nightly-4-19
  cron: 15 9 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      ENABLE_BILLING_ACCOUNT: "yes"
      OPENSHIFT_VERSION: "4.19"
      REGION: us-west-2
      REPLICAS: "3"
    workflow: rosa-gap-analysis-hcp
- as: workflow-classic-nightly-4-20
  cron: 30 9 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "4.20"
      REGION: us-west-2
    workflow: rosa-gap-analysis-classic
- as: workflow-hcp-nightly-4-20
  cron: 45 9 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      ENABLE_BILLING_ACCOUNT: "yes"
      OPENSHIFT_VERSION: "4.20"
      REGION: us-west-2
      REPLICAS: "3"
    workflow: rosa-gap-analysis-hcp
- as: workflow-classic-nightly-4-21
  cron: 0 10 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "4.21"
      REGION: us-west-2
    workflow: rosa-gap-analysis-classic
- as: workflow-hcp-nightly-4-21
  cron: 15 10 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      ENABLE_BILLING_ACCOUNT: "yes"
      OPENSHIFT_VERSION: "4.21"
      REGION: us-west-2
      REPLICAS: "3"
    workflow: rosa-gap-analysis-hcp
- as: workflow-classic-nightly-4-22
  cron: 30 10 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "4.22"
      REGION: us-west-2
    workflow: rosa-gap-analysis-classic
- as: workflow-hcp-nightly-4-22
  cron: 45 10 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      ENABLE_BILLING_ACCOUNT: "yes"
      OPENSHIFT_VERSION: "4.22"
      REGION: us-west-2
      REPLICAS: "3"
    workflow: rosa-gap-analysis-hcp
- as: workflow-classic-nightly-5-0
  cron: 0 11 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "5.0"
      REGION: us-west-2
    workflow: rosa-gap-analysis-classic
- as: workflow-hcp-nightly-5-0
  cron: 15 11 * * *
  steps:
    cluster_profile: rosa-e2e-01
    env:
      CHANNEL_GROUP: nightly
      ENABLE_BILLING_ACCOUNT: "yes"
      OPENSHIFT_VERSION: "5.0"
      REGION: us-west-2
      REPLICAS: "3"
    workflow: rosa-gap-analysis-hcp
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-gap-analysis
  variant: workflow-periodics
