build_root:
  project_image:
    dockerfile_path: ci/Containerfile
  use_build_cache: true
images:
  items:
  - dockerfile_path: ci/Containerfile
    to: rosa-gap-analysis
resources:
  '*':
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: rosa-gap-analysis
