FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.15 AS builder
WORKDIR /go/src/github.com/openshift/byoh
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.15:base
COPY --from=builder /go/src/github.com/openshift/byoh/byoh /usr/bin/
ENTRYPOINT ["/usr/bin/byoh"]
