branch-protection:
  orgs:
    openshift-online:
      repos:
        kube-applier-gcp:
          branches:
            main:
              protect: true
          restrictions:
            teams:
            - openshift-bots
tide:
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    repos:
    - openshift-online/kube-applier-gcp
