base_images:
  ansible:
    name: "5.0"
    namespace: ocp
    tag: ansible
  assisted-service-scripts:
    name: ocm-2.17
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  cli:
    name: "5.0"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.22"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.22"
  tools:
    name: "5.0"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "5.0"
    namespace: ocp
    tag: upi-installer
prowgen:
  expose: true
  private: true
releases:
  latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "5.0"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "5.0"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: logging-e2e-tests-hypershift-powervs-ppc64le
  capabilities:
  - intranet
  cron: '@yearly'
  reporter_config:
    channel: '#logging-qe'
    job_states_to_report:
    - success
    - failure
    - error
    report_template: '{{if eq .Status.State "success"}} :slack-green: Job *{{.Spec.Job}}*
      ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> {{else}} :failed:
      Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs>
      {{end}}'
  steps:
    cluster_profile: openshift-org-aws
    env:
      BASE_DOMAIN: devobscluster.devcluster.openshift.com.
      FORCE_SUCCESS_EXIT: "true"
      LOGGING_TEST_VERSION: "6.6"
      MCE_VERSION: "5.0"
      OPERATORS: |
        [
            {"name": "cluster-logging", "source": "cluster-logging-operator-registry", "channel": "stable-6.6", "install_namespace": "openshift-logging","target_namespaces": "", "operator_group": "openshift-logging"},
            {"name": "loki-operator", "source": "loki-operator-registry", "channel": "stable-6.6", "install_namespace": "openshift-operators-redhat","target_namespaces": "", "operator_group": "openshift-operators-redhat"},
            {"name": "cluster-observability-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-cluster-observability-operator","target_namespaces": "", "operator_group": "openshift-cluster-observability-operator"},
            {"name": "amq-streams", "source": "redhat-operators", "channel": "amq-streams-2.x", "install_namespace": "openshift-operators","target_namespaces": "", "operator_group": ""}
        ]
      TEST_FILTERS: ~Disruptive&;~Longduration&;~AZWIF&;~AZMonitor&;~GCL&
      TEST_IMPORTANCE: Critical|High|Medium
      TEST_PARALLEL: "3"
      TEST_SCENARIOS: sig-openshift-logging
      TEST_TIMEOUT: "35"
    test:
    - chain: hypershift-mce-power-test
    - ref: medik8s-sbr-hypershift-switch-kubeconfig
    - ref: cucushift-installer-rehearse-deploy-nfs-provisioner
    - ref: openshift-logging-catalogsources
    - ref: install-operators
    - chain: openshift-e2e-test-logging-qe
    workflow: cucushift-installer-rehearse-hypershift-powervs-deploy
zz_generated_metadata:
  branch: release-5.0
  org: openshift
  repo: openshift-tests-private
  variant: powervs-stable-openshift-logging-6.6
