binary_build_commands: make build
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.25
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: make unit-test
tests:
- as: unit
  commands: make unit-test
  container:
    from: src
- as: integration
  commands: make integration-test
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: flightctl
  repo: flightctl
