approve:
- repos:
  - openshift-kni/kubernetes-power-manager
  require_self_approval: true
external_plugins:
  openshift-kni/kubernetes-power-manager:
  - endpoint: http://backport-verifier
    events:
    - issue_comment
    - pull_request
    name: backport-verifier
  - endpoint: http://payload-testing-prow-plugin
    events:
    - issue_comment
    name: payload-testing-prow-plugin
  - endpoint: http://pipeline-controller
    events:
    - pull_request
    - issue_comment
    name: pipeline-controller
  - endpoint: http://multi-pr-prow-plugin
    events:
    - issue_comment
    name: multi-pr-prow-plugin
lgtm:
- repos:
  - openshift-kni/kubernetes-power-manager
  review_acts_as_lgtm: true
triggers:
- repos:
  - openshift-kni/kubernetes-power-manager
  trusted_apps:
  - red-hat-konflux
  - openshift-merge-bot
