base_images:
  secrets-store-csi-driver-test:
    name: "5.0"
    namespace: ocp
    tag: secrets-store-csi-driver-test
build_root:
  from_repository: true
releases:
  latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "5.0"
  s390x-latest:
    candidate:
      architecture: s390x
      product: ocp
      stream: nightly
      version: "5.0"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: operator-e2e-s390x-vault-weekly
  capabilities:
  - intranet
  cron: '@weekly'
  steps:
    allow_best_effort_post_steps: true
    cluster_profile: libvirt-s390x-vpn
    dependencies:
      OPENSHIFT_INSTALL_TARGET: release:s390x-latest
    env:
      ARCH: s390x
      BRANCH: "5.0"
      ETCD_DISK_SPEED: slow
      USE_EXTERNAL_DNS: "true"
    test:
    - ref: openshift-e2e-libvirt-s390x-csi-secrets-store-setup-fbc
    - ref: openshift-e2e-libvirt-s390x-csi-secrets-store-test-vault
    workflow: openshift-e2e-libvirt-vpn
zz_generated_metadata:
  branch: main
  org: openshift
  repo: secrets-store-csi-driver-operator
  variant: s390x
