# pylint: disable=R0801

from content.osd_rc_deployments import add_osd_rc_deployments
from content.osd_rc_rbac import add_osd_rc_service_account_resources
from content.osd_files_cache_resources import add_osd_files_cache_resources
from content.osd_files_cache_rbac import add_osd_files_cache_service_account_resources
from content.art_publish_permissions import add_art_publish
from content.art_namespaces_config_updater import add_art_namespace_config_updater_rbac
from content.art_namespaces_rbac import add_imagestream_namespace_rbac
from content.redirect_resources import add_redirect_resources
from content.art_rpm_mirroring_services import add_rpm_mirror_service
from content.bump_versioned_resources import bump_versioned_resources
from content.origin_resources import generate_origin_admin_resources, generate_origin_resources
from content.signer_resources import generate_signer_resources
