branch-protection:
  orgs:
    openshift-online:
      repos:
        ocm-cli:
          branches:
            main:
              protect: true
              required_status_checks:
                contexts:
                - Red Hat Konflux / ocm-cli-enterprise-contract / ocm-cli
                - Red Hat Konflux / ocm-cli-on-pull-request
                - ci/prow/images-images
                - Lint
                - Test (ubuntu-latest)
                - Test (macos-latest)
                - Test (windows-latest)
tide:
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - openshift-online/ocm-cli
