approve:
- repos:
  - openshift-kni/poison-pill
  require_self_approval: false
lgtm:
- repos:
  - openshift-kni/poison-pill
  review_acts_as_lgtm: true
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift-kni/poison-pill
  trusted_apps:
  - red-hat-konflux
  - openshift-merge-bot
