build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.21"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ocp-61589-max-nodes-post-network-expansion
  cron: 0 8 * * 0
  steps:
    cluster_profile: aws-perfscale-qe
    env:
      EXPECTED_READY_NODES: "510"
      MAX_NODES_TARGET: "520"
      TEST_TIMEOUT: 2h
    test:
    - ref: openshift-qe-ocp-61589-max-nodes-network-expansion
    workflow: openshift-qe-installer-aws
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: network-performance-tests
