approve:
- commandHelpLink: https://go.k8s.io/bot-commands
  ignore_review_state: false
  lgtm_acts_as_approve: true
  repos:
  - openshift/sippy
external_plugins:
  openshift/sippy:
  - endpoint: http://muller-boxship
    events:
    - pull_request
    - pull_request_review
    - issue_comment
    name: muller-boxship
lgtm:
- repos:
  - openshift/sippy
  review_acts_as_lgtm: true
plugins:
  openshift/sippy:
    plugins:
    - approve
triggers:
- org_invite:
    prominent: {}
  repos:
  - openshift/sippy
  trusted_apps:
  - openshift-trt
  - openshift-merge-bot
