{
 "title": "Boskos Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account",
    "query": "label_values(boskos_resources{state=\"leased\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Clusters by Platform",
   "type": "graph",
   "description": "sum(label_replace(boskos_resources{state=\"leased\", type=~\"(${account})-quota-slice\"}, \"type\", \"$1\", \"type\", \"(.*)-quota-slice\")) by(type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(boskos_resources{state=\"leased\", type=~\"(${account})-quota-slice\"}, \"type\", \"$1\", \"type\", \"(.*)-quota-slice\")) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "AWS Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "AWS-2 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"aws-2-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"aws-2-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCP Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCP-2 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"gcp-openshift-gce-devel-ci-2-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gcp-openshift-gce-devel-ci-2-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Azure4 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Azure-2 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"azure-2-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"azure-2-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "vSphere Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "vSphere 8 Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"vsphere-8-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"vsphere-8-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Packet.net Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack Vexxhost Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-vexxhost-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-vexxhost-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack VH Mecha Central Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-vh-mecha-central-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-vh-mecha-central-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack NFV Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-nfv-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-nfv-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack HW offload Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-hwoffload-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-hwoffload-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Equinix OCP Metal Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"equinix-ocp-metal-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"equinix-ocp-metal-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}