plugins:
  stolostron/cluster-proxy-addon:
    plugins:
    - dco
triggers:
- org_invite:
    prominent: {}
  repos:
  - stolostron/cluster-proxy-addon
  trusted_apps:
  - red-hat-konflux
  - dependabot
  - openshift-merge-bot
