{
 "title": "Boskos Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "Running Clusters by Platform",
   "type": "graph",
   "description": "sum(kube_pod_container_status_running{pod=~\"e2e(-<regex>(-upgrade)?)?\",container=\"teardown\"})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"(e2e|(.*-aws(-.*)?))\",container=\"teardown\"})",
     "legendFormat": "aws"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*-vsphere(-.*)?\",container=\"teardown\"})",
     "legendFormat": "vsphere"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*-gcp(-.*)?\",container=\"teardown\"})",
     "legendFormat": "gcp"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*-azure(-.*)?\",container=\"teardown\"})",
     "legendFormat": "azure"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*-packet(-.*)?\",container=\"teardown\"})",
     "legendFormat": "packet"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*-openstack(-.*)?\",container=\"teardown\"})",
     "legendFormat": "openstack"
    }
   ]
  },
  {
   "title": "AWS Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"aws-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCP Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gcp-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Azure Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"azure4-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "vSphere Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"vsphere-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Packet.net Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"packet-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OpenStack Quota Leases by State",
   "type": "graph",
   "description": "sum(boskos_resources{type=\"openstack-quota-slice\",state!=\"other\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"openstack-quota-slice\",state!=\"other\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}