{
 "title": "Boskos Server Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "path",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, status)"
   },
   {
    "name": "user-agent",
    "label": "user-agent",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, user_agent)"
   },
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Latency Distribution for HTTP Requests",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(boskos_http_request_duration_seconds_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(boskos_http_request_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(boskos_http_request_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(boskos_http_request_duration_seconds_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Latency Distribution for HTTP Requests For ${path}",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(boskos_http_request_duration_seconds_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(boskos_http_request_duration_seconds_bucket{path=\"${path}\"}[${range}])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(boskos_http_request_duration_seconds_bucket{path=\"${path}\"}[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(boskos_http_request_duration_seconds_bucket{path=\"${path}\"}[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Size Distribution for HTTP Requests",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(boskos_http_response_size_bytes_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(boskos_http_response_size_bytes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(boskos_http_response_size_bytes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(boskos_http_response_size_bytes_bucket[${range}])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Boskos Requests Over Time",
   "type": "graph",
   "description": "sum(increase(boskos_http_request_duration_seconds_bucket[${range}]))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(boskos_http_request_duration_seconds_bucket[${range}]))",
     "legendFormat": "Number of Requests"
    }
   ]
  }
 ]
}