{
 "title": "build-cop dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org",
    "label": "org",
    "query": "label_values(prowjob_state_transitions{job=\"plank\"}, org)"
   },
   {
    "name": "repo",
    "label": "repo",
    "query": "label_values(prowjob_state_transitions{job=\"plank\", org=~\"${org}\"}, repo)"
   },
   {
    "name": "base_ref",
    "label": "base_ref",
    "query": "label_values(prowjob_state_transitions{job=\"plank\", org=~\"${org}\", repo=~\"${repo}\"}, base_ref)"
   },
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Job Success Rates for github.com/${org}/${repo}@${base_ref}",
   "type": "graph",
   "description": "Job success rate for the org/repo/base_ref selected in the templates. Those regexes define our targets for the build-cop.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"branch-.*-images\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"branch-.*-images\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "branch-.*-images"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-4.1\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-4.1\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "release-.*-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-4.2\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-4.2\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "release-.*-4.2"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-upgrade.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*-upgrade.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "release-.*-upgrade.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*4.1.*4.2.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*4.1.*4.2.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "release-.*4.1.*4.2.*"
    }
   ]
  },
  {
   "title": "Presubmit and Postsubmit Job Success Rates for github.com/${org}/${repo}@${base_ref}",
   "type": "graph",
   "description": "Job success rate for the org/repo/base_ref selected in the templates. Those regexes filter out presubmit and postsubmit jobs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"release-.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "release-.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"pull-ci-.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"pull-ci-.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "pull-ci-.*"
    }
   ]
  },
  {
   "title": "Job States by Branch for github.com/${org}/${repo}",
   "type": "graph",
   "description": "Job success rate for all branches and the org/repo selected in the templates.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\", job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"^(master|release-4.[0-9]+|openshift-4.[0-9]+)$\", state=\"success\"}[${range}])) by (base_ref)/sum(rate(prowjob_state_transitions{job=\"plank\", job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"^(master|release-4.[0-9]+|openshift-4.[0-9]+)$\", state=~\"success|failure\"}[${range}]))  by (base_ref)",
     "legendFormat": "{{base_ref}}"
    }
   ]
  },
  {
   "title": "Job States by Type for github.com/${org}/${repo}@${base_ref}",
   "type": "graph",
   "description": "Job success rate for the org/repo/base_ref selected in the templates. Those regexes filter out various types of tests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*images\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*images\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*images"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*e2e.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*e2e.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*e2e.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*upgrade.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*upgrade.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*upgrade.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*unit.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*unit.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*unit.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*integration.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*integration.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*integration.*"
    }
   ]
  },
  {
   "title": "Job States by Platform for github.com/${org}/${repo}@${base_ref}",
   "type": "graph",
   "description": "Job success rate for the org/repo/base_ref selected in the templates. Those regexes filter out various types of testing platforms.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-aws.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-aws.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*-aws.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-vsphere.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-vsphere.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*-vsphere.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-gcp.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-gcp.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*-gcp.*"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-azure.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=\"success\"}[${range}]))/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\".*-azure.*\",job_name!~\"rehearse.*\",org=~\"${org}\",repo=~\"${repo}\",base_ref=~\"${base_ref}\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": ".*-azure.*"
    }
   ]
  }
 ]
}