{
 "title": "ci-operator-configresolver dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "Latency Distribution for HTTP Requests",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(configresolver_http_request_duration_seconds_bucket[15m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(configresolver_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(configresolver_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(configresolver_http_request_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Size Distribution for HTTP Requests",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(configresolver_http_response_size_bytes_bucket[15m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(configresolver_http_response_size_bytes_bucket[15m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(configresolver_http_response_size_bytes_bucket[15m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(configresolver_http_response_size_bytes_bucket[15m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Latency Distribution for Reloading Configs from Disk",
   "type": "graph",
   "description": "histogram_quantile(%s, sum(rate(configresolver_config_reload_duration_seconds_bucket[15m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(configresolver_config_reload_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(configresolver_config_reload_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(configresolver_config_reload_duration_seconds_bucket[15m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Config Resolver Error Rate",
   "type": "graph",
   "description": "sum(increase(configresolver_error_rate[4h])) by (error)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(configresolver_error_rate[4h])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}