{
 "title": "osde2e dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Job Success Rates for osde2e integration regular",
   "type": "graph",
   "description": "Job success rate for osde2e tests on integration running regularly (without an upgrade).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*int-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*int-4.2"
    }
   ]
  },
  {
   "title": "Job Success Rates for osde2e stage regular",
   "type": "graph",
   "description": "Job success rate for osde2e tests on stage running regularly (without an upgrade).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*stage-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*stage-4.2"
    }
   ]
  },
  {
   "title": "Job Success Rates for osde2e production regular",
   "type": "graph",
   "description": "Job success rate for osde2e tests on production running regularly (without an upgrade).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*prod-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*prod-4.2"
    }
   ]
  },
  {
   "title": "Job Success Rates for osde2e integration upgrades",
   "type": "graph",
   "description": "Job success rate for osde2e tests on integration running with upgrades.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*int-4.1-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*int-4.1-4.2"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*int-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*int-4.2-4.2"
    }
   ]
  },
  {
   "title": "Job Success Rates for osde2e stage upgrades",
   "type": "graph",
   "description": "Job success rate for osde2e tests on stage running with upgrades.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*stage-4.1-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*stage-4.1-4.2"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*stage-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*stage-4.2-4.2"
    }
   ]
  },
  {
   "title": "Job Success Rates for osde2e production upgrades",
   "type": "graph",
   "description": "Job success rate for osde2e tests on production running with upgrades.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1-4.1\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*prod-4.1-4.1"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.1-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*prod-4.1-4.2"
    },
    {
     "expr": "sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=\"success\"}[${range}]) or up * 0)/sum(rate(prowjob_state_transitions{job=\"plank\",job_name=~\"periodic.*osde2e.*prod-4.2-4.2\",job_name!~\"rehearse.*\",org=~\"openshift\",repo=~\"osde2e\",base_ref=~\"master\",state=~\"success|failure\"}[${range}]))",
     "legendFormat": "periodic.*osde2e.*prod-4.2-4.2"
    }
   ]
  }
 ]
}