{
 "title": "prow dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "up",
   "type": "graph",
   "description": "sum by(job) (up)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(job) (up)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pod_name:container_cpu_usage:sum{namespace=\"ci\",container_name!=\"POD\"} * on (pod_name) group_left(label_component) label_replace(kube_pod_labels{pod!=\"\",label_app=\"prow\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"ci\",container_name!=\"POD\"} * on (pod_name) group_left(label_component) label_replace(kube_pod_labels{pod!=\"\",label_app=\"prow\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  {
   "title": "Ephemeral storage",
   "type": "graph",
   "description": "Ephemeral storage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pod_name:container_fs_usage_bytes:sum{namespace=\"ci\",container_name!=\"POD\"} * on (pod_name) group_left(label_component) label_replace(kube_pod_labels{pod!=\"\",label_app=\"prow\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")) by (label_component)",
     "legendFormat": "{{label_component}}"
    }
   ]
  }
 ]
}