{
 "title": "tide dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Tide Pool Sizes",
   "type": "graph",
   "description": "The number of PRs eligible for merge in each Tide pool.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pooledprs and ((time() - updatetime) < 240)) by (org, repo, branch)",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(merges_sum[1d]) > 0) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate: Batches Only",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(    rate(merges_sum[1d]) - (sum(rate(merges_bucket{le=\"1\"}[1d])) without (le)) > 0     ) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Pool: openshift/origin:master",
   "type": "graph",
   "description": "Tide stats for the master branch of the openshift/origin repo.\nSpecifically, the number of pooled PRs and the daily merge rate.\n(See the more general graphs for details on how these are calculated.)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pooledprs{org=\"openshift\",repo=\"origin\",branch=\"master\"} and ((time() - updatetime) < 240)) or vector(0)",
     "legendFormat": "Pool size"
    },
    {
     "expr": "sum(rate(merges_sum{org=\"openshift\",repo=\"origin\",branch=\"master\"}[1d])) * 86400",
     "legendFormat": "Daily merge rate"
    }
   ]
  },
  {
   "title": "Tide Processing Time (seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(syncdur and (changes(syncdur[1h]) > 0))",
     "legendFormat": "Sync time"
    },
    {
     "expr": "max(statusupdatedur and (changes(statusupdatedur[1h]) > 0))",
     "legendFormat": "Status update time"
    }
   ]
  }
 ]
}