#!/usr/bin/env bash
set -euo pipefail

echo "=== GCP HCP ArgoCD Sync Validation ==="
echo ""

# Verify kubeconfigs exist (generated by gcp-hcp-generate-kubeconfigs step)
if [[ ! -f "${SHARED_DIR}/region-kubeconfig" ]]; then
  echo "ERROR: Region kubeconfig not found at ${SHARED_DIR}/region-kubeconfig"
  echo "The gcp-hcp-generate-kubeconfigs step must run before this step"
  exit 1
fi

# Set environment variables for Ginkgo test
export REGION_KUBECONFIG="${SHARED_DIR}/region-kubeconfig"

# MC kubeconfig is optional
if [[ -f "${SHARED_DIR}/mc-kubeconfig" ]]; then
  export MC_KUBECONFIG="${SHARED_DIR}/mc-kubeconfig"
  echo "Using MC kubeconfig from ${SHARED_DIR}/mc-kubeconfig"
else
  echo "MC kubeconfig not found - tests will skip management cluster validation"
fi

# Optional: Override sync timeouts (defaults to 30m in test code)
# export REGION_SYNC_TIMEOUT="30m"
# export MC_SYNC_TIMEOUT="30m"

# Run Ginkgo v2 test binary
echo "Running ArgoCD sync validation tests..."
/usr/bin/test-e2e \
  --ginkgo.v \
  --ginkgo.no-color \
  --ginkgo.junit-report="${ARTIFACT_DIR}/junit_argocd_sync.xml" \
  --ginkgo.label-filter="argocd"

echo ""
echo "✓ ArgoCD sync validation completed successfully"
