#!/usr/bin/env bash
set -euo pipefail

echo "=== GCP HCP ArgoCD Sync Validation ==="
echo ""

# Authenticate with WIF credential (already generated by hypershift-gcp-wif-auth step)
echo "Authenticating with WIF credential..."
if [[ ! -f "${SHARED_DIR}/wif-cred.json" ]]; then
  echo "ERROR: WIF credential not found at ${SHARED_DIR}/wif-cred.json"
  echo "The hypershift-gcp-wif-auth step must run before this step"
  exit 1
fi

gcloud auth login --cred-file="${SHARED_DIR}/wif-cred.json" --quiet

# Read terraform outputs written by gcp-hcp-tf-provision step
echo "Reading terraform outputs from provision step..."
REGION_PROJECT=$(<"${SHARED_DIR}/region-project-id")
REGION_CLUSTER_NAME=$(<"${SHARED_DIR}/region-cluster-name")
MC_PROJECT=$(<"${SHARED_DIR}/mc-project-id")
MC_CLUSTER_NAME=$(<"${SHARED_DIR}/mc-cluster-name")
REGION=${GCP_REGION:-us-central1}

echo "  Region Project:       ${REGION_PROJECT}"
echo "  Region Cluster:       ${REGION_CLUSTER_NAME}"
echo "  MC Project:           ${MC_PROJECT}"
echo "  MC Cluster Name:      ${MC_CLUSTER_NAME}"
echo "  Region:               ${REGION}"
echo ""

# Generate region cluster kubeconfig
echo "Generating region cluster kubeconfig..."
gcloud container clusters get-credentials "${REGION_CLUSTER_NAME}" \
  --region="${REGION}" \
  --project="${REGION_PROJECT}" \
  --quiet

# Flatten and export to SHARED_DIR
kubectl config view --flatten --minify > "${SHARED_DIR}/region-kubeconfig"
echo "  ✓ Region kubeconfig written to ${SHARED_DIR}/region-kubeconfig"

# Generate MC cluster kubeconfig (optional - tests skip MC validation if unavailable)
echo "Generating management cluster kubeconfig..."
if gcloud container clusters get-credentials "${MC_CLUSTER_NAME}" \
  --region="${REGION}" \
  --project="${MC_PROJECT}" \
  --quiet 2>/dev/null; then
  kubectl config view --flatten --minify > "${SHARED_DIR}/mc-kubeconfig"
  echo "  ✓ MC kubeconfig written to ${SHARED_DIR}/mc-kubeconfig"
  export MC_KUBECONFIG="${SHARED_DIR}/mc-kubeconfig"
else
  echo "  ⚠ MC cluster unavailable - tests will skip management cluster validation"
fi
echo ""

# Set environment variables for Ginkgo test
export REGION_KUBECONFIG="${SHARED_DIR}/region-kubeconfig"

# Optional: Override sync timeouts (defaults to 30m in test code)
# export REGION_SYNC_TIMEOUT="30m"
# export MC_SYNC_TIMEOUT="30m"

# Run Ginkgo v2 test binary
echo "Running ArgoCD sync validation tests..."
/usr/bin/test-e2e \
  --ginkgo.v \
  --ginkgo.junit-report="${ARTIFACT_DIR}/junit_argocd_sync.xml" \
  --ginkgo.label-filter="argocd"

echo ""
echo "✓ ArgoCD sync validation completed successfully"
