plugins:
  openshift-priv/prom-label-proxy:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - wip
    - yuks
triggers:
- repos:
  - openshift-priv/prom-label-proxy
  trusted_apps:
  - openshift-merge-bot
