plugins:
  openshift-priv/prom-label-proxy:
    plugins:
    - approve
    - golint
    - goose
    - jira
    - owners-label
    - pony
    - sigmention
triggers:
- repos:
  - openshift-priv/prom-label-proxy
  trusted_apps:
  - openshift-merge-bot
