build_root:
  from_repository: true
canonical_go_repository: github.com/openshift/intelliaide-lightspeed-skills
images:
  items:
  - dockerfile_path: Containerfile
    to: intelliaide-lightspeed-skills
promotion:
  to:
  - name: "5.1"
    namespace: ocp-priv
prowgen:
  private: true
releases:
  latest:
    integration:
      include_built_images: true
      name: "5.1"
      namespace: ocp-priv
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: openshift-priv
  repo: intelliaide-lightspeed-skills
