base_images:
  cli:
    name: "4.21"
    namespace: ocp
    tag: cli
  ubi_minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "9"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.21-openshift-4.18
images:
  items:
  - dockerfile_literal: |
      FROM ubi_minimal
      RUN microdnf install -y java-11-openjdk tar jq git openssl python3.11 python3-pip openssh-clients && \
          ln -sf /usr/bin/python3.11 /usr/bin/python3
      RUN curl -L https://github.com/zaproxy/zaproxy/releases/download/v2.17.0/ZAP_2.17.0_Linux.tar.gz > /tmp/ZAP_2.17.0_Linux.tar.gz
      RUN python3 -m ensurepip --upgrade
      RUN pip3 install python-dotenv pyyaml requests
      RUN mkdir -p /usr/local/zap \
        && tar xzvf /tmp/ZAP_2.17.0_Linux.tar.gz -C /usr/local/zap \
        && rm -f /tmp/ZAP_2.17.0_Linux.tar.gz \
        && chmod -R 777 ${HOME}
      ENV PATH $PATH:/usr/local/zap/ZAP_2.17.0
      ENV HOME="/tmp"
    from: ubi_minimal
    to: quay-test-dast
promotion:
  to:
  - namespace: ci
    tag: latest
prowgen:
  expose: true
  private: true
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.21"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: quay-dast-test-quay317
  cron: 0 12 * * 5
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m5.2xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-17-v4-21@sha256:4d329eb8c32ce91a9844fd18959f6076da0e41cb4020544d2537f86dc875ccd7
      QUAY_OPERATOR_CHANNEL: stable-3.17
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-deploy-quay-aws-s3
    - ref: quay-tests-test-quay-dast
    workflow: cucushift-installer-rehearse-aws-ipi
zz_generated_metadata:
  branch: master
  org: quay
  repo: quay-tests
  variant: quay-dast
