base_images:
  cli:
    name: "4.22"
    namespace: ocp
    tag: cli
  upi-installer:
    name: "4.22"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.25-openshift-4.21
prowgen:
  expose: true
  private: true
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.22"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: quay-e2e-tests-quay317-ocp422-virtual-builder
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m5.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-17-v4-21@sha256:c12ff3407a23401be0093f79bbd0005a58b23cb314bee1d3082abba70fd88f51
      NEW_UI_TESTING_COVERAGE: builder
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_BUILDER_IMAGE: image-rbac-proxy.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/redhat-user-workloads/quay-eng-tenant/quay-builder-v3-17@sha256:e0dd8085f094d76189def3d871e16ac79d651fdddf2a73bb9f4be7647861d7f5
      QUAY_OLD_UI_DISABLED: "true"
      QUAY_OPERATOR_CHANNEL: stable-3.17
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_VERSION: "3.17"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-resource-provisioning-tls
    - ref: quay-tests-resource-provisioning-builder
    - ref: quay-tests-quay-deploy-operator
    - ref: quay-tests-quay-deploy-registry-builder
    - ref: quay-tests-test-quay-api
    - ref: quay-tests-test-quay-newui
    - ref: quay-tests-test-quay-e2e
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay-e2e-tests-quay318-ocp422-virtual-builder
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m5.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-18-v4-22@sha256:19de4be82e4dca03f14b83d951951b51e27f5d27e9a8609ff5fb98f62bd8824d
      NEW_UI_TESTING_COVERAGE: builder
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_BUILDER_IMAGE: image-rbac-proxy.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/redhat-user-workloads/quay-eng-tenant/quay-builder-v3-18@sha256:b2be8369944917f0b23d440866f18dd217d2f2f4156b5056209bd3ce0425eeef
      QUAY_OLD_UI_DISABLED: "true"
      QUAY_OPERATOR_CHANNEL: stable-3.18
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_VERSION: "3.18"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-resource-provisioning-tls
    - ref: quay-tests-resource-provisioning-builder
    - ref: quay-tests-quay-deploy-operator
    - ref: quay-tests-quay-deploy-registry-builder
    - ref: quay-tests-test-quay-api
    - ref: quay-tests-test-quay-newui
    - ref: quay-tests-test-quay-e2e
    workflow: cucushift-installer-rehearse-aws-ipi
zz_generated_metadata:
  branch: master
  org: quay
  repo: quay-tests
  variant: ocp-422-quay
