base_images:
  tools:
    name: "4.21"
    namespace: ocp
    tag: tools
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.25-openshift-4.21
images:
  items:
  - dockerfile_path: images/Dockerfile.upgrade
    from: tools
    to: quay-test-operator
promotion:
  to:
  - namespace: ci
    tag: latest
prowgen:
  expose: true
  private: true
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.21"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: quay318-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-18-v4-21@sha256:f7f0740742d6588794af695a50d47cba3579537935d4996e7cf2a94a9deeaf61
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.18
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.18"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay317-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-17-v4-21@sha256:4a1bf7b5365b5d8a7a72e765940d63903cbf6cfd91846b8ff33fe2458015ba17
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.17
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.17"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay316-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-16-v4-21@sha256:3f58b2e2922c278e968643469488abd77bb21de81030952ca1f0abbba1c29476
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.16
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.16"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay315-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-15-v4-21@sha256:9229c544bd8f93345c85bdd1facd9bdec9155c883a7476e3d249d304520acc2d
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.15
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.15"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay314-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-14-v4-21@sha256:3002040ed207ad7b3b9b7ae862a04a082fe17c7e199a8c62163f2dfe09277122
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.14
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.14"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: quay313-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-13-v4-21@sha256:7d408430aa6d720b9ab52e1a5f83b2f7b46944d976a10b522a2443aeebe22171
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.13
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-Upgrade-High|Quay-Upgrade-Medium
      QUAY_VERSION: "3.13"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: cso-quay-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.2xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-17-v4-21@sha256:ad9d78470dedf52a4bb139ead20814e3332f191c0f41c606f446ade14d2805bf
      QUAY_OPERATOR_CHANNEL: stable-3.17
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-CSO-Upgrade-High
      QUAY_VERSION: "3.17"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
- as: qbo-quay-ocp421-upgrade
  cron: '@yearly'
  steps:
    cluster_profile: aws-quay-qe
    env:
      BASE_DOMAIN: quayqe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "6"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      MULTISTAGE_PARAM_OVERRIDE_QUAY_INDEX_IMAGE: quay.io/redhat-user-workloads/quay-eng-tenant/stable-3-17-v4-21@sha256:ad9d78470dedf52a4bb139ead20814e3332f191c0f41c606f446ade14d2805bf
      ODF_OPERATOR_CHANNEL: stable-4.21
      QUAY_OPERATOR_CHANNEL: stable-3.17
      QUAY_OPERATOR_SOURCE: fbc-operator-catalog
      QUAY_UPGRADE_TESTCASE: Quay-QBO-Upgrade-High
      QUAY_VERSION: "3.17"
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-odf
    - ref: quay-tests-quay-deploy-operator
    - ref: quay-tests-quay-deploy-registry-noobaa
    - ref: quay-tests-test-quay-upgrade
    workflow: cucushift-installer-rehearse-aws-ipi
zz_generated_metadata:
  branch: master
  org: quay
  repo: quay-tests
  variant: quay-upgrade
