#!/usr/bin/env groovy

def library_url = "${env.RELEASE_LIBRARY_URL ?: (params.RELEASE_LIBRARY_URL ?: 'github.com/openshift/release-library') }"
def library_ref = "${env.RELEASE_LIBRARY_REF ?: (params.RELEASE_LIBRARY_REF ?: 'master') }"

library "${library_url}@${library_ref}"

def templateBase = "cluster/ci/origin/config"

pipeline {
  agent any

  parameters {
    string(defaultValue: "${env.BUILD_ID}", name: "buildId", description: "The ID that prow sets on a Jenkins job in order to correlate it with a ProwJob")
    string(defaultValue: "${env.ORIGIN_URL ?: 'https://github.com/openshift/origin.git' }", name: "ORIGIN_URL", description: "The URL of the Origin repository to use")
    string(name: "REPO_OWNER", defaultValue:"${env.REPO_OWNER ?: ''}")
    string(name: "REPO_NAME", defaultValue:"${env.REPO_NAME ?: ''}")
    string(name: "PULL_BASE_REF", defaultValue:"${env.PULL_BASE_REF ?: ''}")
    string(name: "PULL_BASE_SHA", defaultValue:"${env.PULL_BASE_SHA ?: ''}")
    string(name: "PULL_REFS", defaultValue:"${env.PULL_REFS ?: 'master'}")
    string(name: "PULL_NUMBER", defaultValue:"${env.PULL_NUMBER ?: ''}")
    string(name: "PULL_PULL_SHA", defaultValue:"${env.PULL_PULL_SHA ?: ''}")
    string(name: "JOB_NICKNAME", defaultValue:"${env.JOB_NICKNAME ?: ''}")
    string(name: "JOB_ARGS", defaultValue:"${env.JOB_ARGS ?: ''}")
    string(name: "MEMORY_LIMIT", defaultValue:"${env.MEMORY_LIMIT ?: ''}")
    string(name: "MEMORY_REQUEST", defaultValue:"${env.MEMORY_REQUEST ?: ''}")
    string(name: "CPU_REQUEST", defaultValue:"${env.CPU_REQUEST ?: ''}")
    string(name: "IMAGE_TAG", defaultValue:"${env.IMAGE_TAG ?: ''}")
    string(name: "RELEASE_LIBRARY_URL", defaultValue: "${library_url}")
    string(name: "RELEASE_LIBRARY_REF", defaultValue: "${library_ref}")
  }

  stages {
    stage ("Configure Variables") {
      steps {
        script {
          this._buildName = buildName(this)
        }
        echo "Build name is ${this._buildName}"
      }
    }
    stage ("Launch Build") {
      steps {
        script {
          def jobName = "${env.PROJECT_NAME ?: 'origin-ci'}-build-origin"
          def buildParams = [
            [$class: "StringParameterValue", name: "ORIGIN_URL", value: params.ORIGIN_URL],
            [$class: "StringParameterValue", name: "BUILD_ID", value: params.BUILD_ID],
            [$class: "StringParameterValue", name: "REPO_OWNER", value: params.REPO_OWNER],
            [$class: "StringParameterValue", name: "REPO_NAME", value: params.REPO_NAME],
            [$class: "StringParameterValue", name: "PULL_BASE_REF", value: params.PULL_BASE_REF],
            [$class: "StringParameterValue", name: "PULL_BASE_SHA", value: params.PULL_BASE_SHA],
            [$class: "StringParameterValue", name: "PULL_REFS", value: params.PULL_REFS],
            [$class: "StringParameterValue", name: "PULL_NUMBER", value: params.PULL_NUMBER],
            [$class: "StringParameterValue", name: "PULL_PULL_SHA", value: params.PULL_PULL_SHA]
          ]
          build job: jobName, parameters: buildParams, wait: false
        }
      }
    }
    stage("Wait For Image") {
      steps {
        waitForTag(this, this._buildName, "${params.IMAGE_TAG}", 7200)
      }
    }
    stage("Run Test") {
      steps {
        ensureLoggingComponents(this)
        script {
          def toolsImageRef = imageStreamTagRef(this, "release-ci", "binary")
          def baseImageRef = imageStreamTagRef(this, this._buildName, "${params.IMAGE_TAG}")
          def pullSecretRef = dockerCfgSecret(this, "default")
          def runId = "${this._buildName}-${params.JOB_NICKNAME}-${currentBuild.number}"
          this._runId = runId

          createTemplate(this, "${templateBase}/tests.yaml",
            "JOB_NICKNAME=${params.JOB_NICKNAME}",
            "JOB_ARGS=${params.JOB_ARGS}",
            "MEMORY_LIMIT=${params.MEMORY_LIMIT}",
            "MEMORY_REQUEST=${params.MEMORY_REQUEST}",
            "CPU_REQUEST=${params.CPU_REQUEST}",
            "BUILD_NAME=${_buildName}",
            "RUN_ID=${runId}",
            "BASE_IMAGE_REF=${baseImageRef}",
            "TOOLS_IMAGE_REF=${toolsImageRef}",
            "PULL_SECRET_NAME=${pullSecretRef}",
            "JOB_NAME=${env.JOB_NAME}",
            "BUILD_NUMBER=${env.BUILD_NUMBER}",
            "REPO_OWNER=${params.REPO_OWNER}",
            "REPO_NAME=${params.REPO_NAME}",
            "PULL_BASE_REF=${params.PULL_BASE_REF}",
            "PULL_BASE_SHA=${params.PULL_BASE_SHA}",
            "PULL_REFS=${params.PULL_REFS}",
            "PULL_NUMBER=${params.PULL_NUMBER}",
            "PULL_PULL_SHA=${params.PULL_PULL_SHA}"
          )

          waitForPods(this, ["run": "${runId}"], 7200)
        }
      }
    }
  }
  post {
    always {
      script {
        openshift.withCluster() {
          def workingDir = pwd()
          def artifactDir = "${workingDir}/artifacts"
          def testPods = openshift.selector("pods", ["run":"${this._runId}"])
          saveArtifacts(this, artifactDir, testPods)
          uploadArtifacts(this, artifactDir)
          try {
            testPods.delete()
          } catch (e) {
            echo "Error cleaning up test pods: ${e}"
          }
        }
      }
    }
  }
}
