approve:
- repos:
  - openshift/bgp-cloud-connector
  require_self_approval: false
lgtm:
- repos:
  - openshift/bgp-cloud-connector
  review_acts_as_lgtm: true
plugins:
  openshift/bgp-cloud-connector:
    plugins:
    - approve
