apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: internal
  namespace: openshift-ingress-operator
spec:
  domain: apps-int.master.ci.devcluster.openshift.com
  routeSelector:
    matchLabels:
      internal: "true"
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal
      dnsManagementPolicy: Managed
