#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

echo "=========================================="
echo "Testing Additional Storage Configurations"
echo "=========================================="

# Verify TechPreviewNoUpgrade is enabled
echo "Verifying TechPreviewNoUpgrade feature gate..."
featureSet=$(oc get featuregate cluster -o jsonpath='{.spec.featureSet}')
if [ "${featureSet}" != "TechPreviewNoUpgrade" ]; then
  echo "ERROR: TechPreviewNoUpgrade not enabled (current: ${featureSet})"
  exit 1
fi
echo "✓ TechPreviewNoUpgrade enabled"

# Verify AdditionalStorageConfig feature is available
echo "Checking if AdditionalStorageConfig feature is enabled..."
if oc get featuregate cluster -o jsonpath='{.status.featureGates[0].enabled[*].name}' | tr ' ' '\n' | grep -q AdditionalStorageConfig; then
  echo "✓ AdditionalStorageConfig feature is enabled"
else
  echo "ERROR: AdditionalStorageConfig feature not found"
  exit 1
fi

# Get test node from setup
nodename=$(cat "${SHARED_DIR}/storage-test-node")
nfsIP=$(cat "${SHARED_DIR}/nfs-server-ip")

echo "Test node: ${nodename}"
echo "NFS IP: ${nfsIP}"

# Verify mounts exist
echo "Verifying storage mounts..."
oc debug node/"${nodename}" -- chroot /host df -h | grep -E "ssd-artifacts|nfs-artifacts" || {
  echo "ERROR: Storage mounts not found"
  exit 1
}
echo "✓ Storage mounts verified"

#=============================================================================
# TEST 1: Additional Layer Stores
#=============================================================================
echo ""
echo "=========================================="
echo "TEST 1: Additional Layer Stores"
echo "=========================================="

cat <<EOF | oc apply -f -
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
  name: test-layer-stores
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  containerRuntimeConfig:
    additionalLayerStores:
      - path: /mnt/ssd-artifacts/layer-store
EOF

echo "✓ Created ContainerRuntimeConfig for layer stores"

# Wait for MCO to process
echo "Waiting for MCO to process ContainerRuntimeConfig..."
sleep 10

# Verify MachineConfig generated
if oc get machineconfig | grep -q containerruntime; then
  echo "✓ MachineConfig generated by MCO"
else
  echo "ERROR: MachineConfig not generated"
  exit 1
fi

# Check ContainerRuntimeConfig status
oc get containerruntimeconfig test-layer-stores -o yaml

#=============================================================================
# TEST 2: Additional Image Stores
#=============================================================================
echo ""
echo "=========================================="
echo "TEST 2: Additional Image Stores"
echo "=========================================="

cat <<EOF | oc apply -f -
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
  name: test-image-stores
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  containerRuntimeConfig:
    additionalImageStores:
      - path: /mnt/ssd-artifacts/image-store
EOF

echo "✓ Created ContainerRuntimeConfig for image stores"

sleep 5
oc get containerruntimeconfig test-image-stores -o yaml

#=============================================================================
# TEST 3: Additional Artifact Stores
#=============================================================================
echo ""
echo "=========================================="
echo "TEST 3: Additional Artifact Stores"
echo "=========================================="

cat <<EOF | oc apply -f -
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
  name: test-artifact-stores
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  containerRuntimeConfig:
    additionalArtifactStores:
      - path: /mnt/nfs-artifacts/artifact-store
EOF

echo "✓ Created ContainerRuntimeConfig for artifact stores"

sleep 5
oc get containerruntimeconfig test-artifact-stores -o yaml

#=============================================================================
# Verify Configuration Applied
#=============================================================================
echo ""
echo "=========================================="
echo "Verifying Configurations"
echo "=========================================="

echo "Waiting for worker MachineConfigPool to update..."
oc wait --for=condition=Updating mcp/worker --timeout=5m || echo "MCP may already be updating"

echo "MachineConfigPool status:"
oc get mcp worker -o yaml | grep -A 10 status:

# List all ContainerRuntimeConfigs
echo ""
echo "All ContainerRuntimeConfigs:"
oc get containerruntimeconfig

# List generated MachineConfigs
echo ""
echo "Generated MachineConfigs:"
oc get machineconfig | grep containerruntime

#=============================================================================
# Summary
#=============================================================================
echo ""
echo "=========================================="
echo "TEST SUMMARY"
echo "=========================================="
echo "✓ TechPreviewNoUpgrade feature gate enabled"
echo "✓ AdditionalStorageConfig feature available"
echo "✓ Storage mounts verified (SSD + NFS)"
echo "✓ Created ContainerRuntimeConfig for layer stores"
echo "✓ Created ContainerRuntimeConfig for image stores"
echo "✓ Created ContainerRuntimeConfig for artifact stores"
echo "✓ MCO processing configurations"
echo ""
echo "NOTE: Full verification requires node update which takes ~10-15 minutes"
echo "      This test validates API acceptance and MCO processing"
echo "=========================================="
