binary_build_commands: make build
build_root:
  image_stream_tag:
    name: builder
    namespace: stolostron
    tag: go1.25-linux
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: verify
  commands: |
    make verify
  container:
    from: src
  skip_if_only_changed: ^\.tekton/|\.rhtap$|^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: unit
  commands: |
    make test
  container:
    from: src
  skip_if_only_changed: ^\.tekton/|\.rhtap$|^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: integration
  commands: make test-integration
  container:
    from: src
  skip_if_only_changed: ^\.tekton/|\.rhtap$|^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: golangci-lint
  commands: |
    export GOCACHE=/tmp/
    export GOLANGCI_LINT_CACHE=/tmp/.cache
    make golangci-lint
  container:
    from: src
  skip_if_only_changed: ^\.tekton/|\.rhtap$|^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: sonar-pre-submit
  commands: |
    export SELF="make -f /opt/build-harness/Makefile.prow"
    export HOME="/tmp"
    make -f /opt/build-harness/Makefile.prow sonar/go/prow
  container:
    from: src
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token
- as: sonar-post-submit
  commands: |
    export SELF="make -f /opt/build-harness/Makefile.prow"
    export HOME="/tmp"
    make -f /opt/build-harness/Makefile.prow sonar/go/prow
  container:
    from: src
  postsubmit: true
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: multicluster-mesh-addon
