# Update the stub RPMs we use in the release images for Golang
build:
	./fake-rpm.sh golang-1.9
	./fake-rpm.sh golang-1.10
	./fake-rpm.sh golang-1.11
	./fake-rpm.sh golang-1.12
	./fake-rpm.sh golang-1.13
	./fake-rpm.sh golang-1.14
.PHONY: build
