build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.25-openshift-4.22
canonical_go_repository: github.com/stolostron/multicluster-observability-operator
images:
  items:
  - dockerfile_path: Dockerfile.interop
    to: multicluster-observability-operator-opp
promotion:
  to:
  - disabled: true
    name: main
    namespace: acm-qe
prowgen:
  private: true
resources:
  '*':
    requests:
      cpu: 100m
      memory: 1Gi
zz_generated_metadata:
  branch: main
  org: openshift-priv
  repo: stolostron-multicluster-observability-operator
  variant: opp
